/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Asociado;
import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import rojerusan.RSPanelsSlider;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Nahomi
 */
public class agregarjf extends javax.swing.JFrame {

    /**
     * Creates new form agregarjf
     */
    private char c;
    private Asociado asociado;
    public agregarjf() {
        asociado = new Asociado();
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        cmbnivelestudioencargado.setModel(asociado.NivEst());
        cmbnivelestudioasociado.setModel(asociado.NivEst());

        if ((tamanio.width == 1920) && (tamanio.height == 1080)) //1920x1080
        {
            this.setLocationRelativeTo(null);
            this.setSize(1255, 705);

        } else if ((tamanio.width == 1366) && (tamanio.height == 768)) //1366x768, 1708x960
        {
            this.setLocationRelativeTo(null);
            this.setSize(1255, 705);
        }
//        this.setLocationRelativeTo(null);
//        this.setSize(1255, 705);
        transparencia();
    }

    public void transparencia() {
        btnsalirdp.setOpaque(false);
        btnsalirdp.setBorderPainted(false);
        btnsalirdp.setContentAreaFilled(false);
        btnminimizardp.setOpaque(false);
        btnminimizardp.setBorderPainted(false);
        btnminimizardp.setContentAreaFilled(false);
        btnhomedp.setOpaque(false);
        btnhomedp.setBorderPainted(false);
        btnhomedp.setContentAreaFilled(false);
        btnmenu.setOpaque(false);
        btnmenu.setBorderPainted(false);
        btnmenu.setContentAreaFilled(false);
        btnsiguienteinfomed.setOpaque(false);
        btnsiguienteinfomed.setBorderPainted(false);
        btnsiguienteinfomed.setContentAreaFilled(false);
        btnaddtel.setOpaque(false);
        btnaddtel.setBorderPainted(false);
        btnaddtel.setContentAreaFilled(false);
        btnatrasdp.setOpaque(false);
        btnatrasdp.setBorderPainted(false);
        btnatrasdp.setContentAreaFilled(false);
        btnsiguientedenc.setOpaque(false);
        btnsiguientedenc.setBorderPainted(false);
        btnsiguientedenc.setContentAreaFilled(false);
        btnsiguienteconteme.setOpaque(false);
        btnsiguienteconteme.setBorderPainted(false);
        btnsiguienteconteme.setContentAreaFilled(false);
        btnsiguientedlab.setOpaque(false);
        btnsiguientedlab.setBorderPainted(false);
        btnsiguientedlab.setContentAreaFilled(false);
        btnsiguientevolu.setOpaque(false);
        btnsiguientevolu.setBorderPainted(false);
        btnsiguientevolu.setContentAreaFilled(false);
        btnatrasinfme.setOpaque(false);
        btnatrasinfme.setBorderPainted(false);
        btnatrasinfme.setContentAreaFilled(false);
        btnatrasdenc.setOpaque(false);
        btnatrasdenc.setBorderPainted(false);
        btnatrasdenc.setContentAreaFilled(false);
        btnatrascontem.setOpaque(false);
        btnatrascontem.setBorderPainted(false);
        btnatrascontem.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnhomedp = new javax.swing.JButton();
        btnminimizardp = new javax.swing.JButton();
        btnsalirdp = new javax.swing.JButton();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jpdatosp = new javax.swing.JPanel();
        btnsiguienteinfomed = new javax.swing.JButton();
        btnaddtel = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        textfieldnombres = new javax.swing.JTextField();
        textfieldedad = new javax.swing.JTextField();
        textfieldapellidos = new javax.swing.JTextField();
        cmbgenero = new javax.swing.JComboBox<>();
        datecfecha = new com.toedter.calendar.JDateChooser();
        textfielddpi = new javax.swing.JTextField();
        textfieldresidencia = new javax.swing.JTextField();
        textfieldcorreo = new javax.swing.JTextField();
        textfieldperfil = new javax.swing.JTextField();
        cmbtalla = new javax.swing.JComboBox<>();
        textfieldtelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpinfomed = new javax.swing.JPanel();
        btnsiguientedenc = new javax.swing.JButton();
        btnatrasdp = new javax.swing.JButton();
        textfieldhospital = new javax.swing.JTextField();
        textfieldpadecimiento1 = new javax.swing.JTextField();
        textfieldpadecimiento2 = new javax.swing.JTextField();
        textfieldpadecimiento3 = new javax.swing.JTextField();
        textfieldpadecimiento4 = new javax.swing.JTextField();
        textfieldalergia1 = new javax.swing.JTextField();
        textfieldalergia2 = new javax.swing.JTextField();
        textfieldalergia3 = new javax.swing.JTextField();
        textfieldalergia4 = new javax.swing.JTextField();
        textfieldalergia5 = new javax.swing.JTextField();
        cmbtipodesangre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jpdenca = new javax.swing.JPanel();
        btnsiguienteconteme = new javax.swing.JButton();
        btnatrasinfme = new javax.swing.JButton();
        textfieldnombreencargado = new javax.swing.JTextField();
        textfieldapellidoencargado = new javax.swing.JTextField();
        textfieldtelefonoencargado = new javax.swing.JTextField();
        cmbnivelestudioencargado = new javax.swing.JComboBox<>();
        textfielddpiencargado = new javax.swing.JTextField();
        textfieldresidenciaencargado = new javax.swing.JTextField();
        textfieldcorreoencargado = new javax.swing.JTextField();
        textfieldocupacionencargado = new javax.swing.JTextField();
        textfieldlugarencargado = new javax.swing.JTextField();
        btnotrotelefonoencargado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jpconteme = new javax.swing.JPanel();
        btnsiguientedlab = new javax.swing.JButton();
        btnatrasdenc = new javax.swing.JButton();
        textfieldnombreemergencia = new javax.swing.JTextField();
        textfieldapellidoemergencia = new javax.swing.JTextField();
        textfieldparentescoemergencia = new javax.swing.JTextField();
        textfieldtelefonoemergencia1 = new javax.swing.JTextField();
        textfieldapellidoemergencia2 = new javax.swing.JTextField();
        textfieldtelefonoemergencia3 = new javax.swing.JTextField();
        textfieldtelefonoemergencia4 = new javax.swing.JTextField();
        textfieldtelefonoemergencia5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpdlabo = new javax.swing.JPanel();
        btnsiguientevolu = new javax.swing.JButton();
        btnatrascontem = new javax.swing.JButton();
        cmbnivelestudioasociado = new javax.swing.JComboBox<>();
        textfieldlugardeestudio = new javax.swing.JTextField();
        textfieldocupacion = new javax.swing.JTextField();
        ttextfieldlugartrabajo = new javax.swing.JTextField();
        btnagregarasociado = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1256, 706));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1255, 705));

        jPanel1.setPreferredSize(new java.awt.Dimension(1275, 725));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        btnhomedp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_30px.png"))); // NOI18N
        btnhomedp.setBorderPainted(false);
        btnhomedp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhomedp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_70px_1.png"))); // NOI18N
        btnhomedp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomedpActionPerformed(evt);
            }
        });

        btnminimizardp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_30px_1.png"))); // NOI18N
        btnminimizardp.setBorderPainted(false);
        btnminimizardp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnminimizardp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_70px.png"))); // NOI18N
        btnminimizardp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizardpActionPerformed(evt);
            }
        });

        btnsalirdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_30px.png"))); // NOI18N
        btnsalirdp.setBorderPainted(false);
        btnsalirdp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalirdp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_70px.png"))); // NOI18N
        btnsalirdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirdpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnhomedp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)
                    .addComponent(btnminimizardp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(btnsalirdp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnhomedp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnminimizardp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsalirdp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        rSPanelsSlider1.setMinimumSize(new java.awt.Dimension(1275, 725));
        rSPanelsSlider1.setPreferredSize(new java.awt.Dimension(1275, 724));

        jpdatosp.setBackground(new java.awt.Color(18, 44, 62));
        jpdatosp.setName("datosp"); // NOI18N
        jpdatosp.setLayout(null);

        btnsiguienteinfomed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguienteinfomed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsiguienteinfomed.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguienteinfomed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteinfomedActionPerformed(evt);
            }
        });
        jpdatosp.add(btnsiguienteinfomed);
        btnsiguienteinfomed.setBounds(1070, 460, 120, 90);

        btnaddtel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Add_Phone_35px.png"))); // NOI18N
        btnaddtel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Add_Phone_70px.png"))); // NOI18N
        jpdatosp.add(btnaddtel);
        btnaddtel.setBounds(870, 450, 110, 100);

        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/Home_70px.png"))); // NOI18N
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_100px.png"))); // NOI18N
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jpdatosp.add(btnmenu);
        btnmenu.setBounds(653, 450, 120, 90);

        textfieldnombres.setBackground(new java.awt.Color(178, 248, 248));
        textfieldnombres.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldnombres.setBorder(null);
        textfieldnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldnombresKeyTyped(evt);
            }
        });
        jpdatosp.add(textfieldnombres);
        textfieldnombres.setBounds(170, 170, 430, 30);

        textfieldedad.setBackground(new java.awt.Color(178, 248, 248));
        textfieldedad.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldedad.setBorder(null);
        textfieldedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldedadKeyTyped(evt);
            }
        });
        jpdatosp.add(textfieldedad);
        textfieldedad.setBounds(120, 300, 90, 30);

        textfieldapellidos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldapellidos.setBorder(null);
        textfieldapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldapellidosKeyTyped(evt);
            }
        });
        jpdatosp.add(textfieldapellidos);
        textfieldapellidos.setBounds(170, 230, 420, 30);

        cmbgenero.setBackground(new java.awt.Color(178, 248, 248));
        cmbgenero.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cmbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cmbgenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbgenero.setOpaque(true);
        jpdatosp.add(cmbgenero);
        cmbgenero.setBounds(380, 300, 190, 33);

        datecfecha.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpdatosp.add(datecfecha);
        datecfecha.setBounds(330, 360, 270, 40);

        textfielddpi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfielddpi.setBorder(null);
        textfielddpi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfielddpiKeyTyped(evt);
            }
        });
        jpdatosp.add(textfielddpi);
        textfielddpi.setBounds(170, 450, 400, 30);

        textfieldresidencia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldresidencia.setBorder(null);
        jpdatosp.add(textfieldresidencia);
        textfieldresidencia.setBounds(210, 520, 360, 30);

        textfieldcorreo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldcorreo.setBorder(null);
        jpdatosp.add(textfieldcorreo);
        textfieldcorreo.setBounds(200, 590, 370, 30);

        textfieldperfil.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldperfil.setBorder(null);
        jpdatosp.add(textfieldperfil);
        textfieldperfil.setBounds(950, 180, 250, 30);

        cmbtalla.setBackground(new java.awt.Color(178, 248, 248));
        cmbtalla.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cmbtalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL" }));
        cmbtalla.setBorder(null);
        jpdatosp.add(cmbtalla);
        cmbtalla.setBounds(870, 250, 60, 33);

        textfieldtelefono.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldtelefono.setBorder(null);
        jpdatosp.add(textfieldtelefono);
        textfieldtelefono.setBounds(880, 320, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datosptam2.jpg"))); // NOI18N
        jpdatosp.add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 710);

        rSPanelsSlider1.add(jpdatosp, "card2");

        jpinfomed.setBackground(new java.awt.Color(18, 44, 62));
        jpinfomed.setName("jpinfomed"); // NOI18N
        jpinfomed.setLayout(null);

        btnsiguientedenc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguientedenc.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguientedenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientedencActionPerformed(evt);
            }
        });
        jpinfomed.add(btnsiguientedenc);
        btnsiguientedenc.setBounds(1100, 470, 120, 90);

        btnatrasdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrasdp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrasdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasdpActionPerformed(evt);
            }
        });
        jpinfomed.add(btnatrasdp);
        btnatrasdp.setBounds(640, 460, 120, 110);

        textfieldhospital.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldhospital.setBorder(null);
        jpinfomed.add(textfieldhospital);
        textfieldhospital.setBounds(50, 250, 530, 23);

        textfieldpadecimiento1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldpadecimiento1.setBorder(null);
        jpinfomed.add(textfieldpadecimiento1);
        textfieldpadecimiento1.setBounds(50, 413, 530, 30);

        textfieldpadecimiento2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldpadecimiento2.setBorder(null);
        jpinfomed.add(textfieldpadecimiento2);
        textfieldpadecimiento2.setBounds(50, 460, 530, 29);

        textfieldpadecimiento3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldpadecimiento3.setBorder(null);
        jpinfomed.add(textfieldpadecimiento3);
        textfieldpadecimiento3.setBounds(50, 513, 530, 30);

        textfieldpadecimiento4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldpadecimiento4.setBorder(null);
        jpinfomed.add(textfieldpadecimiento4);
        textfieldpadecimiento4.setBounds(50, 560, 530, 30);

        textfieldalergia1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldalergia1.setBorder(null);
        jpinfomed.add(textfieldalergia1);
        textfieldalergia1.setBounds(820, 183, 390, 30);

        textfieldalergia2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldalergia2.setBorder(null);
        jpinfomed.add(textfieldalergia2);
        textfieldalergia2.setBounds(650, 232, 560, 30);

        textfieldalergia3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldalergia3.setBorder(null);
        jpinfomed.add(textfieldalergia3);
        textfieldalergia3.setBounds(650, 273, 560, 30);

        textfieldalergia4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldalergia4.setBorder(null);
        jpinfomed.add(textfieldalergia4);
        textfieldalergia4.setBounds(650, 320, 560, 30);

        textfieldalergia5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldalergia5.setBorder(null);
        jpinfomed.add(textfieldalergia5);
        textfieldalergia5.setBounds(650, 360, 470, 30);

        cmbtipodesangre.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cmbtipodesangre.setForeground(new java.awt.Color(255, 255, 255));
        cmbtipodesangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        cmbtipodesangre.setBorder(null);
        jpinfomed.add(cmbtipodesangre);
        cmbtipodesangre.setBounds(790, 530, 270, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/informacionmedicatam2.jpg"))); // NOI18N
        jpinfomed.add(jLabel2);
        jLabel2.setBounds(0, -3, 1260, 710);

        rSPanelsSlider1.add(jpinfomed, "card3");

        jpdenca.setBackground(new java.awt.Color(18, 44, 62));
        jpdenca.setName("jpdenca"); // NOI18N
        jpdenca.setLayout(null);

        btnsiguienteconteme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguienteconteme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguienteconteme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientecontemeActionPerformed(evt);
            }
        });
        jpdenca.add(btnsiguienteconteme);
        btnsiguienteconteme.setBounds(1080, 460, 120, 90);

        btnatrasinfme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrasinfme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrasinfme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasinfmeActionPerformed(evt);
            }
        });
        jpdenca.add(btnatrasinfme);
        btnatrasinfme.setBounds(670, 450, 120, 110);

        textfieldnombreencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldnombreencargado.setBorder(null);
        jpdenca.add(textfieldnombreencargado);
        textfieldnombreencargado.setBounds(160, 170, 440, 30);

        textfieldapellidoencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldapellidoencargado.setBorder(null);
        jpdenca.add(textfieldapellidoencargado);
        textfieldapellidoencargado.setBounds(170, 230, 430, 40);

        textfieldtelefonoencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldtelefonoencargado.setBorder(null);
        jpdenca.add(textfieldtelefonoencargado);
        textfieldtelefonoencargado.setBounds(270, 350, 330, 40);

        cmbnivelestudioencargado.setBackground(new java.awt.Color(178, 248, 248));
        cmbnivelestudioencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cmbnivelestudioencargado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbnivelestudioencargado.setOpaque(true);
        jpdenca.add(cmbnivelestudioencargado);
        cmbnivelestudioencargado.setBounds(254, 292, 340, 40);

        textfielddpiencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfielddpiencargado.setBorder(null);
        jpdenca.add(textfielddpiencargado);
        textfielddpiencargado.setBounds(160, 440, 420, 40);

        textfieldresidenciaencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldresidenciaencargado.setBorder(null);
        jpdenca.add(textfieldresidenciaencargado);
        textfieldresidenciaencargado.setBounds(200, 520, 380, 40);

        textfieldcorreoencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldcorreoencargado.setBorder(null);
        jpdenca.add(textfieldcorreoencargado);
        textfieldcorreoencargado.setBounds(190, 580, 390, 40);

        textfieldocupacionencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldocupacionencargado.setBorder(null);
        jpdenca.add(textfieldocupacionencargado);
        textfieldocupacionencargado.setBounds(660, 220, 550, 40);

        textfieldlugarencargado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldlugarencargado.setBorder(null);
        jpdenca.add(textfieldlugarencargado);
        textfieldlugarencargado.setBounds(660, 320, 550, 40);

        btnotrotelefonoencargado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Add_Phone_35px.png"))); // NOI18N
        btnotrotelefonoencargado.setBorder(null);
        btnotrotelefonoencargado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Add_Phone_70px.png"))); // NOI18N
        jpdenca.add(btnotrotelefonoencargado);
        btnotrotelefonoencargado.setBounds(870, 450, 120, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datosdelencargadotam2.jpg"))); // NOI18N
        jpdenca.add(jLabel3);
        jLabel3.setBounds(0, -3, 1256, 710);

        rSPanelsSlider1.add(jpdenca, "card4");

        jpconteme.setBackground(new java.awt.Color(18, 44, 62));
        jpconteme.setName("jpconteme"); // NOI18N
        jpconteme.setLayout(null);

        btnsiguientedlab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguientedlab.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguientedlab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientedlabActionPerformed(evt);
            }
        });
        jpconteme.add(btnsiguientedlab);
        btnsiguientedlab.setBounds(1080, 460, 120, 90);

        btnatrasdenc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrasdenc.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrasdenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasdencActionPerformed(evt);
            }
        });
        jpconteme.add(btnatrasdenc);
        btnatrasdenc.setBounds(670, 440, 120, 110);

        textfieldnombreemergencia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldnombreemergencia);
        textfieldnombreemergencia.setBounds(170, 160, 430, 40);

        textfieldapellidoemergencia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldapellidoemergencia);
        textfieldapellidoemergencia.setBounds(170, 230, 430, 40);

        textfieldparentescoemergencia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldparentescoemergencia);
        textfieldparentescoemergencia.setBounds(320, 300, 280, 30);

        textfieldtelefonoemergencia1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldtelefonoemergencia1);
        textfieldtelefonoemergencia1.setBounds(180, 360, 150, 30);

        textfieldapellidoemergencia2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldapellidoemergencia2);
        textfieldapellidoemergencia2.setBounds(50, 430, 530, 30);

        textfieldtelefonoemergencia3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldtelefonoemergencia3);
        textfieldtelefonoemergencia3.setBounds(50, 480, 530, 30);

        textfieldtelefonoemergencia4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldtelefonoemergencia4);
        textfieldtelefonoemergencia4.setBounds(50, 530, 530, 30);

        textfieldtelefonoemergencia5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpconteme.add(textfieldtelefonoemergencia5);
        textfieldtelefonoemergencia5.setBounds(50, 570, 530, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/contactodeemergenciatam2.jpg"))); // NOI18N
        jpconteme.add(jLabel4);
        jLabel4.setBounds(0, -3, 1256, 710);
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        rSPanelsSlider1.add(jpconteme, "card5");

        jpdlabo.setBackground(new java.awt.Color(18, 44, 62));
        jpdlabo.setToolTipText("");
        jpdlabo.setName("jpdlabo"); // NOI18N
        jpdlabo.setLayout(null);

        btnsiguientevolu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguientevolu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguientevolu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientevoluActionPerformed(evt);
            }
        });
        jpdlabo.add(btnsiguientevolu);
        btnsiguientevolu.setBounds(1080, 460, 120, 90);

        btnatrascontem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrascontem.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrascontem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrascontemActionPerformed(evt);
            }
        });
        jpdlabo.add(btnatrascontem);
        btnatrascontem.setBounds(670, 440, 120, 110);

        cmbnivelestudioasociado.setBackground(new java.awt.Color(178, 248, 248));
        cmbnivelestudioasociado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cmbnivelestudioasociado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbnivelestudioasociado.setOpaque(true);
        jpdlabo.add(cmbnivelestudioasociado);
        cmbnivelestudioasociado.setBounds(270, 180, 340, 40);
        jpdlabo.add(textfieldlugardeestudio);
        textfieldlugardeestudio.setBounds(70, 320, 530, 30);
        jpdlabo.add(textfieldocupacion);
        textfieldocupacion.setBounds(70, 520, 530, 30);
        jpdlabo.add(ttextfieldlugartrabajo);
        ttextfieldlugartrabajo.setBounds(660, 250, 530, 30);

        btnagregarasociado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/Checkmark_30px.png"))); // NOI18N
        btnagregarasociado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/Checkmark_50px.png"))); // NOI18N
        btnagregarasociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarasociadoActionPerformed(evt);
            }
        });
        jpdlabo.add(btnagregarasociado);
        btnagregarasociado.setBounds(880, 450, 90, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datoslaboralestam2.jpg"))); // NOI18N
        jpdlabo.add(jLabel5);
        jLabel5.setBounds(0, -3, 1250, 710);

        rSPanelsSlider1.add(jpdlabo, "card6");

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 725));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosAsociado()
    {
        String nombre=textfieldnombres.getText();
        String apellido=textfieldapellidos.getText();
        String Dpi=textfielddpi.getText();
        String genero=(String) cmbgenero.getSelectedItem();
        String fecha=getFecha(datecfecha);
        String talla=(String) cmbtalla.getSelectedItem();
        String PerfilFB=textfieldperfil.getText();
        String telefono=textfieldtelefono.getText();
        String email=textfieldcorreo.getText();
        String residencia=textfieldresidencia.getText();
        String nivEst=(String) cmbnivelestudioasociado.getSelectedItem();
        String tipoSangre=(String) cmbtipodesangre.getSelectedItem();
        boolean genero1=false;
        if(genero.equals("Masculino"))
            genero1=true;
        if(asociado.insertar(nombre, apellido, genero1, fecha, email, talla, residencia, true, PerfilFB, tipoSangre, nivEst, Dpi))
            JOptionPane.showMessageDialog(null, "Asociado Ingresado correctamente");
        else
            JOptionPane.showMessageDialog(null, "Error al ingresar el asociado");
    }
    private void btnagregarasociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarasociadoActionPerformed
        /**
         * Proceso para agregar al asociado, todos los datos que están escritos
         * en este frame
         */
        datosAsociado();
    }//GEN-LAST:event_btnagregarasociadoActionPerformed
    private void btnatrascontemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrascontemActionPerformed
        rSPanelsSlider1.setPanelSlider(jpconteme, RSPanelsSlider.DIRECT.RIGHT);

    }//GEN-LAST:event_btnatrascontemActionPerformed

    private void btnsiguientevoluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientevoluActionPerformed

    }//GEN-LAST:event_btnsiguientevoluActionPerformed

    private void btnatrasdencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasdencActionPerformed
        rSPanelsSlider1.setPanelSlider(jpdenca, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnatrasdencActionPerformed

    private void btnsiguientedlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientedlabActionPerformed
        rSPanelsSlider1.setPanelSlider(jpdlabo, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnsiguientedlabActionPerformed

    private void btnatrasinfmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasinfmeActionPerformed
        rSPanelsSlider1.setPanelSlider(jpinfomed, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnatrasinfmeActionPerformed

    private void btnsiguientecontemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientecontemeActionPerformed
        rSPanelsSlider1.setPanelSlider(jpconteme, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnsiguientecontemeActionPerformed

    private void btnatrasdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasdpActionPerformed
        rSPanelsSlider1.setPanelSlider(jpdatosp, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnatrasdpActionPerformed

    private void btnsiguientedencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientedencActionPerformed
        rSPanelsSlider1.setPanelSlider(jpdenca, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnsiguientedencActionPerformed

    private void textfielddpiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfielddpiKeyTyped
        c = evt.getKeyChar();
        if (((int) c >= 0 && (int) c <= 47 && (int) c != 45) || ((int) c >= 58 && (int) c <= 255)) {
            evt.consume();
        }
    }//GEN-LAST:event_textfielddpiKeyTyped

    private void textfieldapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldapellidosKeyTyped
        c = evt.getKeyChar();
        if ((int) c >= 0 && (int) c <= 64 && (int) c != 32) {
            evt.consume();
        }
    }//GEN-LAST:event_textfieldapellidosKeyTyped

    private void textfieldedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldedadKeyTyped
        c = evt.getKeyChar();
        if (((int) c >= 0 && (int) c <= 47) || ((int) c >= 58 && (int) c <= 255)) {
            evt.consume();
        }
    }//GEN-LAST:event_textfieldedadKeyTyped

    private void textfieldnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldnombresKeyTyped
        c = evt.getKeyChar();
        if ((int) c >= 0 && (int) c <= 64 && (int) c != 32) {
            evt.consume();
        }
    }//GEN-LAST:event_textfieldnombresKeyTyped

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir sin guardar cambios?", "¡¡¡ATENCIÓN!!!", WARNING_MESSAGE);
        if (respuesta == 0) {
            menujf m = new menujf();
            m.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnmenuActionPerformed

    
    public String getFecha(JDateChooser jd)
    {
        if(jd.getDate()!=null)
            return formato.format(jd.getDate());
        else
            return null;
    }
    public Date StringFecha(String fecha)
    {
        SimpleDateFormat formato1= new SimpleDateFormat("yyyy-MM-dd");
        Date fechaE=null;
        try {
            fechaE=formato1.parse(fecha);
            return fechaE;
        } catch (ParseException e) {
        }
        return null;
    }
    private boolean validarDatosPersonales() {
        if (textfieldnombres.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo nombre esta vacio, favor de ingresar los nombres");
            textfieldnombres.requestFocus();
            return false;
        } else if (textfieldapellidos.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo apellido esta vacio, favor de ingresar los apellidos");
            textfieldapellidos.requestFocus();
            return false;
        } else if (getFecha(datecfecha)==null) {
            JOptionPane.showMessageDialog(null, "El campo fecha esta vacio, favor de ingresar la fecha de nacimiento");
            datecfecha.requestFocus();
            return false;
        } else {
            return true;
        }
    }
    private void btnsiguienteinfomedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteinfomedActionPerformed
        if (validarDatosPersonales()) {
            rSPanelsSlider1.setPanelSlider(jpinfomed, RSPanelsSlider.DIRECT.LEFT);
        }
    }//GEN-LAST:event_btnsiguienteinfomedActionPerformed

    private void btnhomedpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomedpActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir sin guardar cambios?", "¡¡¡ATENCIÓN!!!", WARNING_MESSAGE);
        if (respuesta == 0) {
            menujf m = new menujf();
            m.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnhomedpActionPerformed

    private void btnminimizardpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizardpActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizardpActionPerformed

    private void btnsalirdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirdpActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir sin guardar cambios?", "¡¡¡ATENCIÓN!!!", WARNING_MESSAGE);
        if (respuesta == 0) {
            menujf m = new menujf();
            m.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnsalirdpActionPerformed

    /**
     * @param args the command line arguments
     */
    private final SimpleDateFormat formato= new SimpleDateFormat("yyyy-MM-dd");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddtel;
    private javax.swing.JButton btnagregarasociado;
    private javax.swing.JButton btnatrascontem;
    private javax.swing.JButton btnatrasdenc;
    private javax.swing.JButton btnatrasdp;
    private javax.swing.JButton btnatrasinfme;
    private javax.swing.JButton btnhomedp;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnminimizardp;
    private javax.swing.JButton btnotrotelefonoencargado;
    private javax.swing.JButton btnsalirdp;
    private javax.swing.JButton btnsiguienteconteme;
    private javax.swing.JButton btnsiguientedenc;
    private javax.swing.JButton btnsiguientedlab;
    private javax.swing.JButton btnsiguienteinfomed;
    private javax.swing.JButton btnsiguientevolu;
    private javax.swing.JComboBox<String> cmbgenero;
    private javax.swing.JComboBox<String> cmbnivelestudioasociado;
    private javax.swing.JComboBox<String> cmbnivelestudioencargado;
    private javax.swing.JComboBox<String> cmbtalla;
    private javax.swing.JComboBox<String> cmbtipodesangre;
    private com.toedter.calendar.JDateChooser datecfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpconteme;
    private javax.swing.JPanel jpdatosp;
    private javax.swing.JPanel jpdenca;
    private javax.swing.JPanel jpdlabo;
    private javax.swing.JPanel jpinfomed;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTextField textfieldalergia1;
    private javax.swing.JTextField textfieldalergia2;
    private javax.swing.JTextField textfieldalergia3;
    private javax.swing.JTextField textfieldalergia4;
    private javax.swing.JTextField textfieldalergia5;
    private javax.swing.JTextField textfieldapellidoemergencia;
    private javax.swing.JTextField textfieldapellidoemergencia2;
    private javax.swing.JTextField textfieldapellidoencargado;
    private javax.swing.JTextField textfieldapellidos;
    private javax.swing.JTextField textfieldcorreo;
    private javax.swing.JTextField textfieldcorreoencargado;
    private javax.swing.JTextField textfielddpi;
    private javax.swing.JTextField textfielddpiencargado;
    private javax.swing.JTextField textfieldedad;
    private javax.swing.JTextField textfieldhospital;
    private javax.swing.JTextField textfieldlugardeestudio;
    private javax.swing.JTextField textfieldlugarencargado;
    private javax.swing.JTextField textfieldnombreemergencia;
    private javax.swing.JTextField textfieldnombreencargado;
    private javax.swing.JTextField textfieldnombres;
    private javax.swing.JTextField textfieldocupacion;
    private javax.swing.JTextField textfieldocupacionencargado;
    private javax.swing.JTextField textfieldpadecimiento1;
    private javax.swing.JTextField textfieldpadecimiento2;
    private javax.swing.JTextField textfieldpadecimiento3;
    private javax.swing.JTextField textfieldpadecimiento4;
    private javax.swing.JTextField textfieldparentescoemergencia;
    private javax.swing.JTextField textfieldperfil;
    private javax.swing.JTextField textfieldresidencia;
    private javax.swing.JTextField textfieldresidenciaencargado;
    private javax.swing.JTextField textfieldtelefono;
    private javax.swing.JTextField textfieldtelefonoemergencia1;
    private javax.swing.JTextField textfieldtelefonoemergencia3;
    private javax.swing.JTextField textfieldtelefonoemergencia4;
    private javax.swing.JTextField textfieldtelefonoemergencia5;
    private javax.swing.JTextField textfieldtelefonoencargado;
    private javax.swing.JTextField ttextfieldlugartrabajo;
    // End of variables declaration//GEN-END:variables
}
