/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author alexd
 */
public class agregarpjf extends javax.swing.JFrame {
    ImageIcon proyecto2 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/proyecto2.jpg")).getImage());
    /**
     * Creates new form agregarpjf
     */
    public agregarpjf() {
        initComponents();
        transparencia();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        if((tamanio.width == 1920) && (tamanio.height == 1080))
        {
            
        }
        else if((tamanio.width == 1366) && (tamanio.height == 768)) //1366.768, alex: 1708.960
        {
            this.setSize(1250, 700);
            jpproyecto.setIcon(proyecto2);
            txtnombreproyecto.setLocation(347, 120);
            txtdesproyecto.setLocation(20, 253);
            btnagregar.setLocation(718, 300);
        }
    }
    public void transparencia()
    {
        txtnombreproyecto.setBackground(new Color(0,0,0,0));
        txtdesproyecto.setBackground(new Color(0,0,0,0));
        btnagregar.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpproyecto = new jcMousePanel.jcMousePanel();
        txtnombreproyecto = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        txtdesproyecto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jpproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/proyecto2.jpg"))); // NOI18N
        jpproyecto.setVisibleLogo(false);
        jpproyecto.setLayout(null);

        txtnombreproyecto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtnombreproyecto.setBorder(null);
        jpproyecto.add(txtnombreproyecto);
        txtnombreproyecto.setBounds(257, 96, 320, 23);

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/Checkmark_black_30px.png"))); // NOI18N
        btnagregar.setBorder(null);
        btnagregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/Checkmark_black_50px.png"))); // NOI18N
        jpproyecto.add(btnagregar);
        btnagregar.setBounds(530, 240, 90, 70);

        txtdesproyecto.setColumns(20);
        txtdesproyecto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtdesproyecto.setRows(5);
        txtdesproyecto.setBorder(null);
        jpproyecto.add(txtdesproyecto);
        txtdesproyecto.setBounds(20, 210, 510, 260);

        getContentPane().add(jpproyecto, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarpjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarpjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarpjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarpjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarpjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private jcMousePanel.jcMousePanel jpproyecto;
    private javax.swing.JTextArea txtdesproyecto;
    private javax.swing.JTextField txtnombreproyecto;
    // End of variables declaration//GEN-END:variables
}
