/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author alexd
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jpadatospersonales = new jcMousePanel.jcMousePanel();
        jpinfomed = new jcMousePanel.jcMousePanel();
        jcdatosencargado = new jcMousePanel.jcMousePanel();
        jpdcontactoem = new jcMousePanel.jcMousePanel();
        jpdatoslaborales = new jcMousePanel.jcMousePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jpadatospersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datosptam2.jpg"))); // NOI18N
        jpadatospersonales.setVisibleLogo(false);
        rSPanelsSlider1.add(jpadatospersonales, "card3");

        jpinfomed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/informacionmedicatam2.jpg"))); // NOI18N
        jpinfomed.setVisibleLogo(false);
        rSPanelsSlider1.add(jpinfomed, "card4");

        jcdatosencargado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datosdelencargadotam2.jpg"))); // NOI18N
        jcdatosencargado.setVisibleLogo(false);
        rSPanelsSlider1.add(jcdatosencargado, "card5");

        jpdcontactoem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/contactodeemergenciatam2.jpg"))); // NOI18N
        jpdcontactoem.setVisibleLogo(false);
        rSPanelsSlider1.add(jpdcontactoem, "card6");

        jpdatoslaborales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datoslaboralestam2.jpg"))); // NOI18N
        jpdatoslaborales.setVisibleLogo(false);
        rSPanelsSlider1.add(jpdatoslaborales, "card7");

        getContentPane().add(rSPanelsSlider1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jcMousePanel.jcMousePanel jcdatosencargado;
    private jcMousePanel.jcMousePanel jpadatospersonales;
    private jcMousePanel.jcMousePanel jpdatoslaborales;
    private jcMousePanel.jcMousePanel jpdcontactoem;
    private jcMousePanel.jcMousePanel jpinfomed;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
