/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import rojerusan.RSPanelsSlider;
import java.awt.Toolkit;

/**
 *
 * @author Nahomi
 */
public class agregarjf extends javax.swing.JFrame {

    /**
     * Creates new form agregarjf
     */
    public agregarjf() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        if((tamanio.width == 1920) && (tamanio.height == 1080)) //1920x1080
        {
            this.setLocationRelativeTo(null);
            this.setSize(1255, 705);
            
        }
        else if((tamanio.width == 1366) && (tamanio.height == 768)) //1366x768, 1708x960
        {
            this.setLocationRelativeTo(null);
            this.setSize(1255, 705);
        }
//        this.setLocationRelativeTo(null);
//        this.setSize(1255, 705);
        transparencia();
    }
    public void transparencia()
    {
        btnsalirdp.setOpaque(false);
        btnsalirdp.setBorderPainted(false);
        btnsalirdp.setContentAreaFilled(false);
        btnminimizardp.setOpaque(false);
        btnminimizardp.setBorderPainted(false);
        btnminimizardp.setContentAreaFilled(false);
        btnhomedp.setOpaque(false);
        btnhomedp.setBorderPainted(false);
        btnhomedp.setContentAreaFilled(false);
        btnmenu.setOpaque(false);
        btnmenu.setBorderPainted(false);
        btnmenu.setContentAreaFilled(false);
        btnsiguienteinfomed.setOpaque(false);
        btnsiguienteinfomed.setBorderPainted(false);
        btnsiguienteinfomed.setContentAreaFilled(false);
        btnaddtel.setOpaque(false);
        btnaddtel.setBorderPainted(false);
        btnaddtel.setContentAreaFilled(false);
        btnsalirinfme.setOpaque(false);
        btnsalirinfme.setBorderPainted(false);
        btnsalirinfme.setContentAreaFilled(false);
        btnminimizarifme.setOpaque(false);
        btnminimizarifme.setBorderPainted(false);
        btnminimizarifme.setContentAreaFilled(false);
        btnhomeinfme.setOpaque(false);
        btnhomeinfme.setBorderPainted(false);
        btnhomeinfme.setContentAreaFilled(false);
        btnatrasdp.setOpaque(false);
        btnatrasdp.setBorderPainted(false);
        btnatrasdp.setContentAreaFilled(false);
        btnsiguientedenc.setOpaque(false);
        btnsiguientedenc.setBorderPainted(false);
        btnsiguientedenc.setContentAreaFilled(false);
        btnsiguienteconteme.setOpaque(false);
        btnsiguienteconteme.setBorderPainted(false);
        btnsiguienteconteme.setContentAreaFilled(false);
        btnsiguientedlab.setOpaque(false);
        btnsiguientedlab.setBorderPainted(false);
        btnsiguientedlab.setContentAreaFilled(false);
        btnsiguientevolu.setOpaque(false);
        btnsiguientevolu.setBorderPainted(false);
        btnsiguientevolu.setContentAreaFilled(false);
        btnatrasinfme.setOpaque(false);
        btnatrasinfme.setBorderPainted(false);
        btnatrasinfme.setContentAreaFilled(false);
        btnatrasdenc.setOpaque(false);
        btnatrasdenc.setBorderPainted(false);
        btnatrasdenc.setContentAreaFilled(false);
        btnatrascontem.setOpaque(false);
        btnatrascontem.setBorderPainted(false);
        btnatrascontem.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jpdatosp = new javax.swing.JPanel();
        btnsiguienteinfomed = new javax.swing.JButton();
        btnaddtel = new javax.swing.JButton();
        btnminimizardp = new javax.swing.JButton();
        btnhomedp = new javax.swing.JButton();
        btnsalirdp = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        textfieldnombres = new javax.swing.JTextField();
        textfieldedad = new javax.swing.JTextField();
        textfieldapellidos = new javax.swing.JTextField();
        cmbgenero = new javax.swing.JComboBox<>();
        datecfecha = new com.toedter.calendar.JDateChooser();
        textfielddpi = new javax.swing.JTextField();
        textfieldresidencia = new javax.swing.JTextField();
        textfieldcorreo = new javax.swing.JTextField();
        textfieldperfil = new javax.swing.JTextField();
        cmbtalla = new javax.swing.JComboBox<>();
        textfieldtelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpinfomed = new javax.swing.JPanel();
        btnhomeinfme = new javax.swing.JButton();
        btnminimizarifme = new javax.swing.JButton();
        btnsalirinfme = new javax.swing.JButton();
        btnsiguientedenc = new javax.swing.JButton();
        btnatrasdp = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jpdenca = new javax.swing.JPanel();
        btnsiguienteconteme = new javax.swing.JButton();
        btnatrasinfme = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jpconteme = new javax.swing.JPanel();
        btnsiguientedlab = new javax.swing.JButton();
        btnatrasdenc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jpdlabo = new javax.swing.JPanel();
        btnsiguientevolu = new javax.swing.JButton();
        btnatrascontem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1256, 706));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1255, 705));

        jPanel1.setPreferredSize(new java.awt.Dimension(1275, 725));
        jPanel1.setLayout(new java.awt.CardLayout());

        rSPanelsSlider1.setMinimumSize(new java.awt.Dimension(1275, 725));
        rSPanelsSlider1.setPreferredSize(new java.awt.Dimension(1275, 724));

        jpdatosp.setBackground(new java.awt.Color(18, 44, 62));
        jpdatosp.setName("datosp"); // NOI18N
        jpdatosp.setLayout(null);

        btnsiguienteinfomed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguienteinfomed.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguienteinfomed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteinfomedActionPerformed(evt);
            }
        });
        jpdatosp.add(btnsiguienteinfomed);
        btnsiguienteinfomed.setBounds(1070, 460, 120, 90);

        btnaddtel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Add_Phone_35px.png"))); // NOI18N
        btnaddtel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Add_Phone_70px.png"))); // NOI18N
        jpdatosp.add(btnaddtel);
        btnaddtel.setBounds(870, 450, 110, 100);

        btnminimizardp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_30px_1.png"))); // NOI18N
        btnminimizardp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_70px.png"))); // NOI18N
        btnminimizardp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizardpActionPerformed(evt);
            }
        });
        jpdatosp.add(btnminimizardp);
        btnminimizardp.setBounds(1100, 0, 80, 70);

        btnhomedp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_30px.png"))); // NOI18N
        btnhomedp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_70px_1.png"))); // NOI18N
        btnhomedp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomedpActionPerformed(evt);
            }
        });
        jpdatosp.add(btnhomedp);
        btnhomedp.setBounds(1019, 0, 80, 70);

        btnsalirdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_30px.png"))); // NOI18N
        btnsalirdp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_70px.png"))); // NOI18N
        btnsalirdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirdpActionPerformed(evt);
            }
        });
        jpdatosp.add(btnsalirdp);
        btnsalirdp.setBounds(1180, 0, 70, 70);

        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/Home_70px.png"))); // NOI18N
        btnmenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_100px.png"))); // NOI18N
        jpdatosp.add(btnmenu);
        btnmenu.setBounds(653, 450, 120, 90);

        textfieldnombres.setBackground(new java.awt.Color(178, 248, 248));
        textfieldnombres.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldnombres.setBorder(null);
        jpdatosp.add(textfieldnombres);
        textfieldnombres.setBounds(170, 170, 430, 30);

        textfieldedad.setBackground(new java.awt.Color(178, 248, 248));
        textfieldedad.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldedad.setBorder(null);
        jpdatosp.add(textfieldedad);
        textfieldedad.setBounds(120, 300, 90, 30);

        textfieldapellidos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldapellidos.setBorder(null);
        jpdatosp.add(textfieldapellidos);
        textfieldapellidos.setBounds(170, 230, 420, 30);

        cmbgenero.setBackground(new java.awt.Color(178, 248, 248));
        cmbgenero.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cmbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jpdatosp.add(cmbgenero);
        cmbgenero.setBounds(380, 300, 190, 29);

        datecfecha.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jpdatosp.add(datecfecha);
        datecfecha.setBounds(330, 360, 270, 40);

        textfielddpi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfielddpi.setBorder(null);
        jpdatosp.add(textfielddpi);
        textfielddpi.setBounds(170, 450, 400, 30);

        textfieldresidencia.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldresidencia.setBorder(null);
        jpdatosp.add(textfieldresidencia);
        textfieldresidencia.setBounds(210, 520, 360, 30);

        textfieldcorreo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldcorreo.setBorder(null);
        jpdatosp.add(textfieldcorreo);
        textfieldcorreo.setBounds(200, 590, 370, 30);

        textfieldperfil.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldperfil.setBorder(null);
        jpdatosp.add(textfieldperfil);
        textfieldperfil.setBounds(950, 180, 250, 30);

        cmbtalla.setBackground(new java.awt.Color(178, 248, 248));
        cmbtalla.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cmbtalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL" }));
        jpdatosp.add(cmbtalla);
        cmbtalla.setBounds(870, 250, 60, 29);

        textfieldtelefono.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        textfieldtelefono.setBorder(null);
        jpdatosp.add(textfieldtelefono);
        textfieldtelefono.setBounds(880, 320, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datosptam2.jpg"))); // NOI18N
        jpdatosp.add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 710);

        rSPanelsSlider1.add(jpdatosp, "card2");

        jpinfomed.setBackground(new java.awt.Color(18, 44, 62));
        jpinfomed.setName("jpinfomed"); // NOI18N
        jpinfomed.setLayout(null);

        btnhomeinfme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_30px.png"))); // NOI18N
        btnhomeinfme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_70px_1.png"))); // NOI18N
        btnhomeinfme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeinfmeActionPerformed(evt);
            }
        });
        jpinfomed.add(btnhomeinfme);
        btnhomeinfme.setBounds(1019, 0, 80, 70);

        btnminimizarifme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_30px_1.png"))); // NOI18N
        btnminimizarifme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_70px.png"))); // NOI18N
        btnminimizarifme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizarifmeActionPerformed(evt);
            }
        });
        jpinfomed.add(btnminimizarifme);
        btnminimizarifme.setBounds(1100, 0, 80, 70);

        btnsalirinfme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_30px.png"))); // NOI18N
        btnsalirinfme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_70px.png"))); // NOI18N
        btnsalirinfme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirinfmeActionPerformed(evt);
            }
        });
        jpinfomed.add(btnsalirinfme);
        btnsalirinfme.setBounds(1180, 0, 70, 70);

        btnsiguientedenc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguientedenc.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguientedenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientedencActionPerformed(evt);
            }
        });
        jpinfomed.add(btnsiguientedenc);
        btnsiguientedenc.setBounds(1100, 470, 120, 90);

        btnatrasdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrasdp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrasdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasdpActionPerformed(evt);
            }
        });
        jpinfomed.add(btnatrasdp);
        btnatrasdp.setBounds(640, 460, 120, 110);

        jTextField1.setText("jTextField1");
        jpinfomed.add(jTextField1);
        jTextField1.setBounds(720, 270, 430, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/informacionmedicatam2.jpg"))); // NOI18N
        jpinfomed.add(jLabel2);
        jLabel2.setBounds(0, -3, 1260, 710);

        rSPanelsSlider1.add(jpinfomed, "card3");

        jpdenca.setBackground(new java.awt.Color(18, 44, 62));
        jpdenca.setName("jpdenca"); // NOI18N
        jpdenca.setLayout(null);

        btnsiguienteconteme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguienteconteme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguienteconteme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientecontemeActionPerformed(evt);
            }
        });
        jpdenca.add(btnsiguienteconteme);
        btnsiguienteconteme.setBounds(1080, 460, 120, 90);

        btnatrasinfme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrasinfme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrasinfme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasinfmeActionPerformed(evt);
            }
        });
        jpdenca.add(btnatrasinfme);
        btnatrasinfme.setBounds(670, 450, 120, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datosdelencargadotam2.jpg"))); // NOI18N
        jpdenca.add(jLabel3);
        jLabel3.setBounds(0, -3, 1256, 710);

        rSPanelsSlider1.add(jpdenca, "card4");

        jpconteme.setBackground(new java.awt.Color(18, 44, 62));
        jpconteme.setName("jpconteme"); // NOI18N
        jpconteme.setLayout(null);

        btnsiguientedlab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguientedlab.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguientedlab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientedlabActionPerformed(evt);
            }
        });
        jpconteme.add(btnsiguientedlab);
        btnsiguientedlab.setBounds(1080, 460, 120, 90);

        btnatrasdenc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrasdenc.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrasdenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasdencActionPerformed(evt);
            }
        });
        jpconteme.add(btnatrasdenc);
        btnatrasdenc.setBounds(670, 440, 120, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/contactodeemergenciatam2.jpg"))); // NOI18N
        jpconteme.add(jLabel4);
        jLabel4.setBounds(0, -3, 1256, 710);
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        rSPanelsSlider1.add(jpconteme, "card5");

        jpdlabo.setBackground(new java.awt.Color(18, 44, 62));
        jpdlabo.setToolTipText("");
        jpdlabo.setName("jpdlabo"); // NOI18N
        jpdlabo.setLayout(null);

        btnsiguientevolu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_70px.png"))); // NOI18N
        btnsiguientevolu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Redo_100px.png"))); // NOI18N
        btnsiguientevolu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguientevoluActionPerformed(evt);
            }
        });
        jpdlabo.add(btnsiguientevolu);
        btnsiguientevolu.setBounds(1080, 460, 120, 90);

        btnatrascontem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_70px.png"))); // NOI18N
        btnatrascontem.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa/icons8_Undo_100px.png"))); // NOI18N
        btnatrascontem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrascontemActionPerformed(evt);
            }
        });
        jpdlabo.add(btnatrascontem);
        btnatrascontem.setBounds(670, 440, 120, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/datoslaboralestam2.jpg"))); // NOI18N
        jpdlabo.add(jLabel5);
        jLabel5.setBounds(0, -3, 1250, 710);

        rSPanelsSlider1.add(jpdlabo, "card6");

        jPanel1.add(rSPanelsSlider1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteinfomedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteinfomedActionPerformed
       rSPanelsSlider1.setPanelSlider(jpinfomed, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnsiguienteinfomedActionPerformed

    private void btnsalirdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirdpActionPerformed
        JOptionPane.showMessageDialog(null, "¿Desea salir sin guardar cambios?", "¡¡¡ATENCIÓN!!!", WARNING_MESSAGE);     
        this.dispose();
    }//GEN-LAST:event_btnsalirdpActionPerformed

    private void btnhomedpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomedpActionPerformed
        JOptionPane.showMessageDialog(null, "¿Desea salir sin guardar cambios?", "¡¡¡ATENCIÓN!!!", WARNING_MESSAGE);     
        this.dispose();
        menujf menu = new menujf();
        menu.setVisible(true);
    }//GEN-LAST:event_btnhomedpActionPerformed

    private void btnminimizardpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizardpActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizardpActionPerformed

    private void btnhomeinfmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeinfmeActionPerformed
        JOptionPane.showMessageDialog(null, "¿Desea salir sin guardar cambios?", "¡¡¡ATENCIÓN!!!", WARNING_MESSAGE);     
        this.dispose();
        menujf menu = new menujf();
        menu.setVisible(true);
    }//GEN-LAST:event_btnhomeinfmeActionPerformed

    private void btnminimizarifmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizarifmeActionPerformed
         this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizarifmeActionPerformed

    private void btnsalirinfmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirinfmeActionPerformed
        JOptionPane.showMessageDialog(null, "¿Desea salir sin guardar cambios?", "¡¡¡ATENCIÓN!!!", WARNING_MESSAGE);     
        this.dispose();
    }//GEN-LAST:event_btnsalirinfmeActionPerformed

    private void btnsiguientedencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientedencActionPerformed
        rSPanelsSlider1.setPanelSlider(jpdenca, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnsiguientedencActionPerformed

    private void btnatrasdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasdpActionPerformed
      rSPanelsSlider1.setPanelSlider(jpdatosp, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnatrasdpActionPerformed

    private void btnsiguientecontemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientecontemeActionPerformed
        rSPanelsSlider1.setPanelSlider(jpconteme, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnsiguientecontemeActionPerformed

    private void btnsiguientedlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientedlabActionPerformed
        rSPanelsSlider1.setPanelSlider(jpdlabo, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnsiguientedlabActionPerformed

    private void btnsiguientevoluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguientevoluActionPerformed
        
    }//GEN-LAST:event_btnsiguientevoluActionPerformed

    private void btnatrasinfmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasinfmeActionPerformed
        rSPanelsSlider1.setPanelSlider(jpinfomed, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnatrasinfmeActionPerformed

    private void btnatrasdencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasdencActionPerformed
        rSPanelsSlider1.setPanelSlider(jpdenca, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnatrasdencActionPerformed

    private void btnatrascontemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrascontemActionPerformed
        rSPanelsSlider1.setPanelSlider(jpconteme, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnatrascontemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddtel;
    private javax.swing.JButton btnatrascontem;
    private javax.swing.JButton btnatrasdenc;
    private javax.swing.JButton btnatrasdp;
    private javax.swing.JButton btnatrasinfme;
    private javax.swing.JButton btnhomedp;
    private javax.swing.JButton btnhomeinfme;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnminimizardp;
    private javax.swing.JButton btnminimizarifme;
    private javax.swing.JButton btnsalirdp;
    private javax.swing.JButton btnsalirinfme;
    private javax.swing.JButton btnsiguienteconteme;
    private javax.swing.JButton btnsiguientedenc;
    private javax.swing.JButton btnsiguientedlab;
    private javax.swing.JButton btnsiguienteinfomed;
    private javax.swing.JButton btnsiguientevolu;
    private javax.swing.JComboBox<String> cmbgenero;
    private javax.swing.JComboBox<String> cmbtalla;
    private com.toedter.calendar.JDateChooser datecfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpconteme;
    private javax.swing.JPanel jpdatosp;
    private javax.swing.JPanel jpdenca;
    private javax.swing.JPanel jpdlabo;
    private javax.swing.JPanel jpinfomed;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTextField textfieldapellidos;
    private javax.swing.JTextField textfieldcorreo;
    private javax.swing.JTextField textfielddpi;
    private javax.swing.JTextField textfieldedad;
    private javax.swing.JTextField textfieldnombres;
    private javax.swing.JTextField textfieldperfil;
    private javax.swing.JTextField textfieldresidencia;
    private javax.swing.JTextField textfieldtelefono;
    // End of variables declaration//GEN-END:variables
}
