/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.BusquedasVoluntarios;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Nahomi
 */
public class busquedasjf extends javax.swing.JFrame {

    /**
     * Creates new form busquedasjf
     */
    private BusquedasVoluntarios busquedas;
    private Boolean activo=true;
    public busquedasjf() {
        busquedas = new BusquedasVoluntarios();
        initComponents();
        tablebvnombre.setModel(busquedas.BNombre("", tablebvnombre, "",true));
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnsalir = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnminimizar = new javax.swing.JButton();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jpmenua = new javax.swing.JPanel();
        btnbvnombre = new javax.swing.JButton();
        btnbvexbecarios = new javax.swing.JButton();
        btnbvnoexbecarios = new javax.swing.JButton();
        btnbvanio = new javax.swing.JButton();
        btnbvedad = new javax.swing.JButton();
        btnbvgenero = new javax.swing.JButton();
        btnbvprograma = new javax.swing.JButton();
        btnbvpromocionbeca = new javax.swing.JButton();
        btnbvocupacion = new javax.swing.JButton();
        btnrmenua = new javax.swing.JButton();
        lbmenua = new javax.swing.JLabel();
        jpvactivosina = new javax.swing.JPanel();
        txtbvnombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jsbvnombre = new javax.swing.JScrollPane();
        tablebvnombre = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbactivo = new javax.swing.JComboBox<>();
        lbvnombre = new javax.swing.JLabel();
        jpgeneral = new javax.swing.JPanel();
        txtbvactivos = new javax.swing.JTextField();
        jsbvactivos = new javax.swing.JScrollPane();
        tablebvactivos = new javax.swing.JTable();
        txtbvactivos1 = new javax.swing.JTextField();
        lbvactivos = new javax.swing.JLabel();
        jpvexbnexb = new javax.swing.JPanel();
        txtnvexbnexb = new javax.swing.JTextField();
        jsbvinactivos = new javax.swing.JScrollPane();
        tablebvinactivos = new javax.swing.JTable();
        txtavexbnexb = new javax.swing.JTextField();
        cmbexbnexb = new javax.swing.JComboBox<>();
        lbvinactivos = new javax.swing.JLabel();
        jpvanio = new javax.swing.JPanel();
        txtbvanio = new javax.swing.JTextField();
        jsbvanio = new javax.swing.JScrollPane();
        tablebvanio = new javax.swing.JTable();
        lbvanio = new javax.swing.JLabel();
        jpvedad = new javax.swing.JPanel();
        jsbvedad = new javax.swing.JScrollPane();
        tablebvedad = new javax.swing.JTable();
        cmbedad = new javax.swing.JComboBox<>();
        lbvedad = new javax.swing.JLabel();
        jpvgenero = new javax.swing.JPanel();
        jsbvgenero = new javax.swing.JScrollPane();
        tablebvgenero = new javax.swing.JTable();
        cmbgenero = new javax.swing.JComboBox<>();
        lbvgenero = new javax.swing.JLabel();
        jpvprograma = new javax.swing.JPanel();
        jsbvprograma = new javax.swing.JScrollPane();
        tablebvprograma = new javax.swing.JTable();
        cmbprograma = new javax.swing.JComboBox<>();
        lbvprograma = new javax.swing.JLabel();
        jpvpromocionbeca = new javax.swing.JPanel();
        jsbvpromocionbeca = new javax.swing.JScrollPane();
        tablebvpromocionbeca = new javax.swing.JTable();
        cmbapromocion = new javax.swing.JComboBox<>();
        lbvpromocionbeca = new javax.swing.JLabel();
        jpvocupacion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablebvocupacion = new javax.swing.JTable();
        cmbocupacion = new javax.swing.JComboBox<>();
        lbvocupacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1565, 880));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(1565, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(1250, 700));
        jPanel1.setLayout(null);

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_30px.png"))); // NOI18N
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_70px.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir);
        btnsalir.setBounds(1180, 0, 70, 70);

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_30px.png"))); // NOI18N
        btnhome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_70px_1.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomedpActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(1019, 0, 80, 70);

        btnminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_30px_1.png"))); // NOI18N
        btnminimizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_70px.png"))); // NOI18N
        btnminimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnminimizar);
        btnminimizar.setBounds(1100, 0, 80, 70);

        rSPanelsSlider1.setMaximumSize(new java.awt.Dimension(1565, 880));
        rSPanelsSlider1.setMinimumSize(new java.awt.Dimension(1250, 700));
        rSPanelsSlider1.setPreferredSize(new java.awt.Dimension(1250, 700));

        jpmenua.setMaximumSize(new java.awt.Dimension(1565, 880));
        jpmenua.setMinimumSize(new java.awt.Dimension(1250, 700));
        jpmenua.setName("jpmenua"); // NOI18N
        jpmenua.setLayout(null);

        btnbvnombre.setText("volutario nombre");
        btnbvnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvnombreMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvnombre);
        btnbvnombre.setBounds(60, 260, 140, 50);

        btnbvexbecarios.setText("voluntarios exbecarios");
        btnbvexbecarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvexbecariosMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvexbecarios);
        btnbvexbecarios.setBounds(790, 480, 160, 50);

        btnbvnoexbecarios.setText("voluntarios no exbecarios");
        btnbvnoexbecarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvnoexbecariosMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvnoexbecarios);
        btnbvnoexbecarios.setBounds(540, 240, 180, 50);

        btnbvanio.setText("voluntarios por año");
        btnbvanio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvanioMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvanio);
        btnbvanio.setBounds(300, 250, 150, 40);

        btnbvedad.setText("voluntarios por edad");
        btnbvedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvedadMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvedad);
        btnbvedad.setBounds(800, 270, 150, 40);

        btnbvgenero.setText("voluntarios por genero");
        btnbvgenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvgeneroMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvgenero);
        btnbvgenero.setBounds(1020, 280, 170, 40);

        btnbvprograma.setText("voluntarios por programa");
        btnbvprograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvprogramaMouseClicked(evt);
            }
        });
        btnbvprograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbvprogramaActionPerformed(evt);
            }
        });
        jpmenua.add(btnbvprograma);
        btnbvprograma.setBounds(280, 500, 180, 40);

        btnbvpromocionbeca.setText("voluntarios por promocion de beca");
        btnbvpromocionbeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvpromocionbecaMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvpromocionbeca);
        btnbvpromocionbeca.setBounds(520, 500, 240, 40);

        btnbvocupacion.setText("voluntarios por ocupacion");
        btnbvocupacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbvocupacionMouseClicked(evt);
            }
        });
        jpmenua.add(btnbvocupacion);
        btnbvocupacion.setBounds(40, 510, 190, 40);

        btnrmenua.setText("jButton12");
        btnrmenua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrmenuaActionPerformed(evt);
            }
        });
        jpmenua.add(btnrmenua);
        btnrmenua.setBounds(1040, 460, 130, 90);

        lbmenua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/menubusquedastam2.jpg"))); // NOI18N
        jpmenua.add(lbmenua);
        lbmenua.setBounds(0, 0, 1250, 700);

        rSPanelsSlider1.add(jpmenua, "card9");

        jpvactivosina.setMaximumSize(new java.awt.Dimension(1565, 880));
        jpvactivosina.setMinimumSize(new java.awt.Dimension(1250, 700));
        jpvactivosina.setName("jpvactivosina"); // NOI18N
        jpvactivosina.setPreferredSize(new java.awt.Dimension(1250, 700));
        jpvactivosina.setLayout(null);

        txtbvnombre.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtbvnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbvnombreKeyPressed(evt);
            }
        });
        jpvactivosina.add(txtbvnombre);
        txtbvnombre.setBounds(310, 200, 340, 40);

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });
        jpvactivosina.add(txtApellido);
        txtApellido.setBounds(310, 270, 340, 40);

        tablebvnombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DPI", "Email", "Genero", "Fecha de nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jsbvnombre.setViewportView(tablebvnombre);
        if (tablebvnombre.getColumnModel().getColumnCount() > 0) {
            tablebvnombre.getColumnModel().getColumn(0).setResizable(false);
            tablebvnombre.getColumnModel().getColumn(1).setResizable(false);
            tablebvnombre.getColumnModel().getColumn(3).setResizable(false);
            tablebvnombre.getColumnModel().getColumn(4).setResizable(false);
            tablebvnombre.getColumnModel().getColumn(5).setResizable(false);
        }

        jpvactivosina.add(jsbvnombre);
        jsbvnombre.setBounds(120, 340, 1010, 320);

        jLabel1.setText("Nombre:");
        jpvactivosina.add(jLabel1);
        jLabel1.setBounds(160, 170, 50, 16);

        jLabel2.setText("Apellido:");
        jpvactivosina.add(jLabel2);
        jLabel2.setBounds(160, 220, 50, 16);

        cmbactivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbactivoActionPerformed(evt);
            }
        });
        jpvactivosina.add(cmbactivo);
        cmbactivo.setBounds(850, 240, 190, 30);

        lbvnombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vactnact2.jpg"))); // NOI18N
        jpvactivosina.add(lbvnombre);
        lbvnombre.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpvactivosina, "card3");

        jpgeneral.setMaximumSize(new java.awt.Dimension(1565, 880));
        jpgeneral.setMinimumSize(new java.awt.Dimension(1250, 700));
        jpgeneral.setName("jpgeneral"); // NOI18N
        jpgeneral.setPreferredSize(new java.awt.Dimension(1250, 700));
        jpgeneral.setLayout(null);

        txtbvactivos.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtbvactivos.setText("jTextField1");
        jpgeneral.add(txtbvactivos);
        txtbvactivos.setBounds(310, 250, 410, 40);

        tablebvactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsbvactivos.setViewportView(tablebvactivos);

        jpgeneral.add(jsbvactivos);
        jsbvactivos.setBounds(110, 320, 1030, 350);

        txtbvactivos1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtbvactivos1.setText("jTextField1");
        jpgeneral.add(txtbvactivos1);
        txtbvactivos1.setBounds(310, 190, 410, 40);

        lbvactivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vinfog2.jpg"))); // NOI18N
        jpgeneral.add(lbvactivos);
        lbvactivos.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpgeneral, "card4");

        jpvexbnexb.setName("jpvexbnexb"); // NOI18N
        jpvexbnexb.setLayout(null);

        txtnvexbnexb.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtnvexbnexb.setText("jTextField1");
        jpvexbnexb.add(txtnvexbnexb);
        txtnvexbnexb.setBounds(300, 200, 350, 50);

        tablebvinactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsbvinactivos.setViewportView(tablebvinactivos);

        jpvexbnexb.add(jsbvinactivos);
        jsbvinactivos.setBounds(110, 350, 1030, 310);

        txtavexbnexb.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtavexbnexb.setText("jTextField1");
        jpvexbnexb.add(txtavexbnexb);
        txtavexbnexb.setBounds(300, 270, 350, 50);

        cmbexbnexb.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        cmbexbnexb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpvexbnexb.add(cmbexbnexb);
        cmbexbnexb.setBounds(840, 240, 210, 40);

        lbvinactivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vexbnb2.jpg"))); // NOI18N
        jpvexbnexb.add(lbvinactivos);
        lbvinactivos.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpvexbnexb, "card5");

        jpvanio.setName("jpvanio"); // NOI18N
        jpvanio.setLayout(null);

        txtbvanio.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtbvanio.setText("jTextField1");
        jpvanio.add(txtbvanio);
        txtbvanio.setBounds(360, 140, 650, 30);

        tablebvanio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsbvanio.setViewportView(tablebvanio);

        jpvanio.add(jsbvanio);
        jsbvanio.setBounds(100, 260, 1090, 440);

        lbvanio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vainicio2.jpg"))); // NOI18N
        jpvanio.add(lbvanio);
        lbvanio.setBounds(-32768, -32768, 1250, 700);

        rSPanelsSlider1.add(jpvanio, "card8");

        jpvedad.setName("jpvedad"); // NOI18N
        jpvedad.setLayout(null);

        tablebvedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsbvedad.setViewportView(tablebvedad);

        jpvedad.add(jsbvedad);
        jsbvedad.setBounds(100, 280, 1040, 380);

        cmbedad.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        cmbedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpvedad.add(cmbedad);
        cmbedad.setBounds(250, 200, 200, 40);

        lbvedad.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbvedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vedad2.jpg"))); // NOI18N
        jpvedad.add(lbvedad);
        lbvedad.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpvedad, "card9");

        jpvgenero.setName("jpvgenero"); // NOI18N
        jpvgenero.setLayout(null);

        tablebvgenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsbvgenero.setViewportView(tablebvgenero);

        jpvgenero.add(jsbvgenero);
        jsbvgenero.setBounds(110, 270, 1030, 390);

        cmbgenero.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        cmbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpvgenero.add(cmbgenero);
        cmbgenero.setBounds(250, 200, 260, 30);

        lbvgenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vgenero2.jpg"))); // NOI18N
        jpvgenero.add(lbvgenero);
        lbvgenero.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpvgenero, "card10");

        jpvprograma.setName("jpvprograma"); // NOI18N
        jpvprograma.setLayout(null);

        tablebvprograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsbvprograma.setViewportView(tablebvprograma);

        jpvprograma.add(jsbvprograma);
        jsbvprograma.setBounds(110, 280, 1040, 380);

        cmbprograma.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        cmbprograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpvprograma.add(cmbprograma);
        cmbprograma.setBounds(300, 210, 340, 50);

        lbvprograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vprograma2.jpg"))); // NOI18N
        jpvprograma.add(lbvprograma);
        lbvprograma.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpvprograma, "card11");

        jpvpromocionbeca.setName("jpvpromocionbeca"); // NOI18N
        jpvpromocionbeca.setLayout(null);

        tablebvpromocionbeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsbvpromocionbeca.setViewportView(tablebvpromocionbeca);

        jpvpromocionbeca.add(jsbvpromocionbeca);
        jsbvpromocionbeca.setBounds(100, 280, 1040, 380);

        cmbapromocion.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        cmbapromocion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpvpromocionbeca.add(cmbapromocion);
        cmbapromocion.setBounds(370, 200, 210, 40);

        lbvpromocionbeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vpromocion2.jpg"))); // NOI18N
        jpvpromocionbeca.add(lbvpromocionbeca);
        lbvpromocionbeca.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpvpromocionbeca, "card12");

        jpvocupacion.setName("jpvocupacion"); // NOI18N
        jpvocupacion.setLayout(null);

        tablebvocupacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablebvocupacion);

        jpvocupacion.add(jScrollPane1);
        jScrollPane1.setBounds(100, 290, 1040, 380);

        cmbocupacion.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        cmbocupacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpvocupacion.add(cmbocupacion);
        cmbocupacion.setBounds(300, 200, 420, 40);

        lbvocupacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/busquedas/vocupacion2.jpg"))); // NOI18N
        jpvocupacion.add(lbvocupacion);
        lbvocupacion.setBounds(0, 0, 1370, 740);

        rSPanelsSlider1.add(jpvocupacion, "card13");

        jPanel1.add(rSPanelsSlider1);
        rSPanelsSlider1.setBounds(0, 0, 1370, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbvprogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbvprogramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbvprogramaActionPerformed

    private void btnbvnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvnombreMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvactivosina, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvnombreMouseClicked

    private void btnbvexbecariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvexbecariosMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvexbnexb, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvexbecariosMouseClicked

    private void btnbvnoexbecariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvnoexbecariosMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvactivosina, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvnoexbecariosMouseClicked

    private void btnbvanioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvanioMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvanio, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvanioMouseClicked

    private void btnbvedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvedadMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvedad, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvedadMouseClicked

    private void btnbvgeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvgeneroMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvgenero, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvgeneroMouseClicked

    private void btnbvprogramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvprogramaMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvprograma, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvprogramaMouseClicked

    private void btnbvpromocionbecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvpromocionbecaMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvpromocionbeca, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvpromocionbecaMouseClicked

    private void btnbvocupacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbvocupacionMouseClicked
        rSPanelsSlider1.setPanelSlider(jpvocupacion, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnbvocupacionMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnhomedpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomedpActionPerformed
        rSPanelsSlider1.setPanelSlider(jpmenua, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnhomedpActionPerformed

    private void btnminimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizarActionPerformed

    private void btnrmenuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrmenuaActionPerformed
        rSPanelsSlider1.setPanelSlider(jpmenua, RSPanelsSlider.DIRECT.RIGHT);
    }//GEN-LAST:event_btnrmenuaActionPerformed

    private void txtbvnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbvnombreKeyPressed
        String act=(String)cmbactivo.getSelectedItem();
        if(act.equals("Activo"))
            activo=true;
        else
            activo=false;
            
        tablebvnombre.setModel(busquedas.BNombre(txtbvnombre.getText(), tablebvnombre, txtApellido.getText(),activo));
    }//GEN-LAST:event_txtbvnombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        String act=(String)cmbactivo.getSelectedItem();
        activo = act.equals("Activo");
        tablebvnombre.setModel(busquedas.BNombre(txtbvnombre.getText(), tablebvnombre, txtApellido.getText(),activo));
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void cmbactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbactivoActionPerformed
        String act=(String)cmbactivo.getSelectedItem();
        activo = act.equals("Activo");
        tablebvnombre.setModel(busquedas.BNombre(txtbvnombre.getText(), tablebvnombre, txtApellido.getText(),activo));
    }//GEN-LAST:event_cmbactivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busquedasjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busquedasjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busquedasjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busquedasjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busquedasjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbvanio;
    private javax.swing.JButton btnbvedad;
    private javax.swing.JButton btnbvexbecarios;
    private javax.swing.JButton btnbvgenero;
    private javax.swing.JButton btnbvnoexbecarios;
    private javax.swing.JButton btnbvnombre;
    private javax.swing.JButton btnbvocupacion;
    private javax.swing.JButton btnbvprograma;
    private javax.swing.JButton btnbvpromocionbeca;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnminimizar;
    private javax.swing.JButton btnrmenua;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbactivo;
    private javax.swing.JComboBox<String> cmbapromocion;
    private javax.swing.JComboBox<String> cmbedad;
    private javax.swing.JComboBox<String> cmbexbnexb;
    private javax.swing.JComboBox<String> cmbgenero;
    private javax.swing.JComboBox<String> cmbocupacion;
    private javax.swing.JComboBox<String> cmbprograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpgeneral;
    private javax.swing.JPanel jpmenua;
    private javax.swing.JPanel jpvactivosina;
    private javax.swing.JPanel jpvanio;
    private javax.swing.JPanel jpvedad;
    private javax.swing.JPanel jpvexbnexb;
    private javax.swing.JPanel jpvgenero;
    private javax.swing.JPanel jpvocupacion;
    private javax.swing.JPanel jpvprograma;
    private javax.swing.JPanel jpvpromocionbeca;
    private javax.swing.JScrollPane jsbvactivos;
    private javax.swing.JScrollPane jsbvanio;
    private javax.swing.JScrollPane jsbvedad;
    private javax.swing.JScrollPane jsbvgenero;
    private javax.swing.JScrollPane jsbvinactivos;
    private javax.swing.JScrollPane jsbvnombre;
    private javax.swing.JScrollPane jsbvprograma;
    private javax.swing.JScrollPane jsbvpromocionbeca;
    private javax.swing.JLabel lbmenua;
    private javax.swing.JLabel lbvactivos;
    private javax.swing.JLabel lbvanio;
    private javax.swing.JLabel lbvedad;
    private javax.swing.JLabel lbvgenero;
    private javax.swing.JLabel lbvinactivos;
    private javax.swing.JLabel lbvnombre;
    private javax.swing.JLabel lbvocupacion;
    private javax.swing.JLabel lbvprograma;
    private javax.swing.JLabel lbvpromocionbeca;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTable tablebvactivos;
    private javax.swing.JTable tablebvanio;
    private javax.swing.JTable tablebvedad;
    private javax.swing.JTable tablebvgenero;
    private javax.swing.JTable tablebvinactivos;
    private javax.swing.JTable tablebvnombre;
    private javax.swing.JTable tablebvocupacion;
    private javax.swing.JTable tablebvprograma;
    private javax.swing.JTable tablebvpromocionbeca;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtavexbnexb;
    private javax.swing.JTextField txtbvactivos;
    private javax.swing.JTextField txtbvactivos1;
    private javax.swing.JTextField txtbvanio;
    private javax.swing.JTextField txtbvnombre;
    private javax.swing.JTextField txtnvexbnexb;
    // End of variables declaration//GEN-END:variables
}
