/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Usuario;
import Clases.antecedentesMedicos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import org.apache.commons.codec.digest.DigestUtils;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Nahomi
 */
public class inicio_login extends javax.swing.JFrame {

    /**
     * Creates new form inicio_login
     */
    private Usuario us;
    Font fuente = new Font("Yu Gothic UI Light", Font.BOLD, 25);
    Font fuente2 = new Font("Yu Gothic UI Light", Font.BOLD, 15);
    ImageIcon iniciotam1 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/iniciointerfaz.jpg")).getImage());
    ImageIcon logintam1 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/login.jpg")).getImage());

    public inicio_login() {
        initComponents();
        us = new Usuario();     //instancio la clase usuario.
        this.setResizable(false);
        CMBUsuarios.setModel(us.usuarios()); //Le doy el modelo al combo box de usuarios.
        CMBUsuarios.setBackground(new Color(0, 0, 0, 0));
        PSTcontrasenia.setBackground(new Color(0, 0, 0, 0));
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        if ((tamanio.width == 1920) && (tamanio.height == 1080)) {
            this.setSize(1568, 880); //1568 880 1250 700
            rSPanelsSlider1.setSize(1568, 880);
            jpinicio.setSize(1568, 880);
            jplogin.setSize(1568, 880);
            lbinicio.setSize(1568, 880);
            lblogin.setSize(1568, 880);
            lbinicio.setIcon(iniciotam1);
            lblogin.setIcon(logintam1);
            btnsiguiente.setLocation(1400, 700);
            btnadmin.setLocation(190, 560);
            btncomite.setLocation(430, 560);
            btningresar.setLocation(850, 550);
            btnfpassword.setLocation(1470, 635);
            PSTcontrasenia.setLocation(950, 436);
            PSTcontrasenia.setFont(fuente);
            CMBUsuarios.setLocation(980, 335);
            CMBUsuarios.setFont(fuente);
        }
        this.setLocationRelativeTo(null);
        transparencia();
    }

    public void transparencia() {
//        btnminimizar.setOpaque(false);
//        btnminimizar.setContentAreaFilled(false);
//        btnminimizar.setBorderPainted(false);
//        btnsalir.setOpaque(false);
//        btnsalir.setContentAreaFilled(false);
//        btnsalir.setBorderPainted(false);
        btnsiguiente.setOpaque(false);
        btnsiguiente.setContentAreaFilled(false);
        btnsiguiente.setBorderPainted(false);
//        btnatras.setOpaque(false);
//        btnatras.setContentAreaFilled(false);
//        btnatras.setBorderPainted(false);
        btnadmin.setOpaque(false);
        btnadmin.setContentAreaFilled(false);
        btnadmin.setBorderPainted(false);
        btncomite.setOpaque(false);
        btncomite.setContentAreaFilled(false);
        btncomite.setBorderPainted(false);
        btningresar.setOpaque(false);
        btningresar.setContentAreaFilled(false);
        btningresar.setBorderPainted(false);
        btnfpassword.setOpaque(false);
        btnfpassword.setContentAreaFilled(false);
        btnfpassword.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelf = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jpinicio = new javax.swing.JPanel();
        btnsiguiente = new javax.swing.JButton();
        lbinicio = new javax.swing.JLabel();
        jplogin = new javax.swing.JPanel();
        CMBUsuarios = new javax.swing.JComboBox<>();
        PSTcontrasenia = new javax.swing.JPasswordField();
        btnadmin = new javax.swing.JButton();
        btningresar = new javax.swing.JButton();
        btncomite = new javax.swing.JButton();
        btnfpassword = new javax.swing.JButton();
        lblogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);

        panelf.setLayout(null);

        rSPanelsSlider1.setMaximumSize(new java.awt.Dimension(1565, 880));
        rSPanelsSlider1.setMinimumSize(new java.awt.Dimension(250, 700));
        rSPanelsSlider1.setPreferredSize(new java.awt.Dimension(1250, 700));

        jpinicio.setName("jpinicio"); // NOI18N
        jpinicio.setLayout(null);

        btnsiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inicio/icons8_Right_70px.png"))); // NOI18N
        btnsiguiente.setName("btnsiguiente"); // NOI18N
        btnsiguiente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inicio/icons8_Right_100px.png"))); // NOI18N
        btnsiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsiguienteMouseClicked(evt);
            }
        });
        jpinicio.add(btnsiguiente);
        btnsiguiente.setBounds(1050, 530, 103, 79);

        lbinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/iniciotam2.jpg"))); // NOI18N
        lbinicio.setText("jLabel1");
        jpinicio.add(lbinicio);
        lbinicio.setBounds(0, -30, 1290, 770);

        rSPanelsSlider1.add(jpinicio, "card4");

        jplogin.setName("jplogin"); // NOI18N
        jplogin.setLayout(null);

        CMBUsuarios.setBackground(new java.awt.Color(0, 102, 153));
        CMBUsuarios.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        CMBUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        CMBUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ejemplo@gmail.com", "ejemplo2@hotmail.com", "ejemplo3@outlook.com", "ejemplo4@yahoo.com" }));
        CMBUsuarios.setBorder(null);
        jplogin.add(CMBUsuarios);
        CMBUsuarios.setBounds(660, 245, 390, 40);

        PSTcontrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        PSTcontrasenia.setForeground(new java.awt.Color(0, 255, 255));
        PSTcontrasenia.setText("jPasswordField1");
        PSTcontrasenia.setBorder(null);
        PSTcontrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PSTcontraseniaKeyPressed(evt);
            }
        });
        jplogin.add(PSTcontrasenia);
        PSTcontrasenia.setBounds(710, 325, 330, 25);

        btnadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Admin_Settings_Male_70px.png"))); // NOI18N
        btnadmin.setName("btnadmin"); // NOI18N
        btnadmin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Admin_Settings_Male_100px.png"))); // NOI18N
        jplogin.add(btnadmin);
        btnadmin.setBounds(130, 380, 120, 110);

        btningresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_In_Progress_70px.png"))); // NOI18N
        btningresar.setName("btningresar"); // NOI18N
        btningresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_In_Progress_100px.png"))); // NOI18N
        btningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btningresarMouseClicked(evt);
            }
        });
        jplogin.add(btningresar);
        btningresar.setBounds(630, 380, 103, 110);

        btncomite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_User_Groups_70px.png"))); // NOI18N
        btncomite.setMaximumSize(new java.awt.Dimension(130, 130));
        btncomite.setMinimumSize(new java.awt.Dimension(130, 130));
        btncomite.setName("btncomite"); // NOI18N
        btncomite.setPreferredSize(new java.awt.Dimension(130, 130));
        btncomite.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_User_Groups_100px.png"))); // NOI18N
        jplogin.add(btncomite);
        btncomite.setBounds(300, 380, 130, 110);

        btnfpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Forgot_Password_70px_1.png"))); // NOI18N
        btnfpassword.setName("btnfpassword"); // NOI18N
        btnfpassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Forgot_Password_100px.png"))); // NOI18N
        jplogin.add(btnfpassword);
        btnfpassword.setBounds(1090, 480, 120, 110);

        lblogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/logintam2.jpg"))); // NOI18N
        lblogin.setText("jLabel1");
        jplogin.add(lblogin);
        lblogin.setBounds(0, 0, 1250, 700);

        rSPanelsSlider1.add(jplogin, "card4");

        panelf.add(rSPanelsSlider1);
        rSPanelsSlider1.setBounds(0, 0, 1250, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelf, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelf, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsiguienteMouseClicked
        if (us.ContarUsuarios()==0) {
            Registrarjf registrar = new Registrarjf();
            registrar.setVisible(true);
            this.dispose();
        }else{
            rSPanelsSlider1.setPanelSlider(jplogin, RSPanelsSlider.DIRECT.LEFT);
        }
        
    }//GEN-LAST:event_btnsiguienteMouseClicked

    private void btningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btningresarMouseClicked
        InicioSecion();
    }//GEN-LAST:event_btningresarMouseClicked

    private void PSTcontraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PSTcontraseniaKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == 10)
            InicioSecion();
    }//GEN-LAST:event_PSTcontraseniaKeyPressed
    /**
     * metodo que verifica la si la contraseña del usurio es la misma en la BD.
     */
    private void InicioSecion() {
        String usuario = (String) CMBUsuarios.getSelectedItem();
        if (us.verificarSesion(DigestUtils.md5Hex(PSTcontrasenia.getText()), usuario)) {
            this.dispose();
            splashjf s = new splashjf();
            menujf m = new menujf();
            this.dispose();
            s.setVisible(true);
            s.setLocationRelativeTo(null);
            try {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(10);
                    s.porcentajec.setText(Integer.toString(i) + "%");
                    s.barracargando.setValue(i);
                    if (i == 100) {
                        s.dispose();
                        m.setVisible(true);
                    }
                }

            } catch (InterruptedException e) {

            }

        } else {
            JOptionPane.showMessageDialog(null, "Error al ingresar la contraseña", "Error", WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new inicio_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CMBUsuarios;
    private javax.swing.JPasswordField PSTcontrasenia;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btncomite;
    private javax.swing.JButton btnfpassword;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JPanel jpinicio;
    private javax.swing.JPanel jplogin;
    private javax.swing.JLabel lbinicio;
    private javax.swing.JLabel lblogin;
    private javax.swing.JPanel panelf;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
