/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import org.apache.commons.codec.digest.DigestUtils;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Nahomi
 */
public class inicio_login extends javax.swing.JFrame {

    /**
     * Creates new form inicio_login
     */
    private Usuario us;
    Font fuente = new Font("Yu Gothic UI Light",Font.BOLD, 25);
    Font fuente2 = new Font("Yu Gothic UI Light", Font.BOLD, 15);
    ImageIcon iniciotam1 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/iniciointerfaz.jpg")).getImage());
    ImageIcon logintam1 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/login.jpg")).getImage());
    ImageIcon iniciotam2 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/iniciotam2.jpg")).getImage());
    ImageIcon logintam2 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/logintam2.jpg")).getImage());
    

    public inicio_login() {
        initComponents();
        us = new Usuario();     //instancio la clase usuario.
        this.setResizable(false);
        CMBUsuarios.setModel(us.usuarios()); //Le doy el modelo al combo box de usuarios.
        CMBUsuarios.setBackground(new Color(0, 0, 0, 0));
        PSTcontrasenia.setBackground(new Color(0, 0, 0, 0));
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        if((tamanio.width == 1920)&&(tamanio.height ==1080))
        {
            this.setSize(1685,985);
            inicio.setIcon(iniciotam1);
            login.setIcon(logintam1);
            btnsiguiente.setLocation(1450, 770);
            btnadmin.setLocation(190, 560);
            btncomite.setLocation(430, 560);
            btningresar.setLocation(850, 550);
            btnfpassword.setLocation(1470, 635);
            PSTcontrasenia.setLocation(950, 436);
            PSTcontrasenia.setFont(fuente);
            CMBUsuarios.setLocation(980, 335);
            CMBUsuarios.setFont(fuente);
        }
        else if((tamanio.width == 1708) && (tamanio.height == 960)) //1366.760, alex: 1708.960
        {
            this.setSize(1256, 706);
            inicio.setIcon(iniciotam2);
            login.setIcon(logintam2);
            btnsiguiente.setLocation(1050, 530);
            btnadmin.setLocation(130, 376);
            btncomite.setLocation(300, 376);
            CMBUsuarios.setLocation(660,233);
            CMBUsuarios.setFont(fuente2);
            PSTcontrasenia.setLocation(710, 312);
            btningresar.setLocation(622, 370);
            btnfpassword.setLocation(1090, 440);
        }

        this.setLocationRelativeTo(null);
        transparencia();
    }

    public void transparencia() {
//        btnminimizar.setOpaque(false);
//        btnminimizar.setContentAreaFilled(false);
//        btnminimizar.setBorderPainted(false);
//        btnsalir.setOpaque(false);
//        btnsalir.setContentAreaFilled(false);
//        btnsalir.setBorderPainted(false);
        btnsiguiente.setOpaque(false);
        btnsiguiente.setContentAreaFilled(false);
        btnsiguiente.setBorderPainted(false);
//        btnatras.setOpaque(false);
//        btnatras.setContentAreaFilled(false);
//        btnatras.setBorderPainted(false);
        btnadmin.setOpaque(false);
        btnadmin.setContentAreaFilled(false);
        btnadmin.setBorderPainted(false);
        btncomite.setOpaque(false);
        btncomite.setContentAreaFilled(false);
        btncomite.setBorderPainted(false);
        btningresar.setOpaque(false);
        btningresar.setContentAreaFilled(false);
        btningresar.setBorderPainted(false);
        btnfpassword.setOpaque(false);
        btnfpassword.setContentAreaFilled(false);
        btnfpassword.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interfaz = new jcMousePanel.jcMousePanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        inicio = new jcMousePanel.jcMousePanel();
        btnsiguiente = new javax.swing.JButton();
        login = new jcMousePanel.jcMousePanel();
        CMBUsuarios = new javax.swing.JComboBox<>();
        PSTcontrasenia = new javax.swing.JPasswordField();
        btnadmin = new javax.swing.JButton();
        btncomite = new javax.swing.JButton();
        btningresar = new javax.swing.JButton();
        btnfpassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(724, 635));

        interfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/iniciointerfaz.jpg"))); // NOI18N
        interfaz.setLayout(new java.awt.CardLayout());

        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/iniciointerfaz.jpg"))); // NOI18N
        inicio.setName("inicio"); // NOI18N
        inicio.setVisibleLogo(false);
        inicio.setLayout(null);

        btnsiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inicio/icons8_Right_70px.png"))); // NOI18N
        btnsiguiente.setName("btnsiguiente"); // NOI18N
        btnsiguiente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inicio/icons8_Right_100px.png"))); // NOI18N
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });
        inicio.add(btnsiguiente);
        btnsiguiente.setBounds(417, 344, 103, 79);

        rSPanelsSlider1.add(inicio, "card2");

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/login.jpg"))); // NOI18N
        login.setName("login"); // NOI18N
        login.setVisibleLogo(false);
        login.setLayout(null);

        CMBUsuarios.setBackground(new java.awt.Color(0, 102, 153));
        CMBUsuarios.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        CMBUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        CMBUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ejemplo@gmail.com", "ejemplo2@hotmail.com", "ejemplo3@outlook.com", "ejemplo4@yahoo.com" }));
        CMBUsuarios.setBorder(null);
        CMBUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBUsuariosActionPerformed(evt);
            }
        });
        login.add(CMBUsuarios);
        CMBUsuarios.setBounds(760, 280, 390, 40);

        PSTcontrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        PSTcontrasenia.setForeground(new java.awt.Color(0, 255, 255));
        PSTcontrasenia.setText("jPasswordField1");
        PSTcontrasenia.setBorder(null);
        login.add(PSTcontrasenia);
        PSTcontrasenia.setBounds(730, 370, 330, 25);

        btnadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Admin_Settings_Male_70px.png"))); // NOI18N
        btnadmin.setName("btnadmin"); // NOI18N
        btnadmin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Admin_Settings_Male_100px.png"))); // NOI18N
        login.add(btnadmin);
        btnadmin.setBounds(130, 440, 120, 110);

        btncomite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_User_Groups_70px.png"))); // NOI18N
        btncomite.setMaximumSize(new java.awt.Dimension(130, 130));
        btncomite.setMinimumSize(new java.awt.Dimension(130, 130));
        btncomite.setName("btncomite"); // NOI18N
        btncomite.setPreferredSize(new java.awt.Dimension(130, 130));
        btncomite.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_User_Groups_100px.png"))); // NOI18N
        login.add(btncomite);
        btncomite.setBounds(320, 440, 130, 110);

        btningresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_In_Progress_70px.png"))); // NOI18N
        btningresar.setName("btningresar"); // NOI18N
        btningresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_In_Progress_100px.png"))); // NOI18N
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        login.add(btningresar);
        btningresar.setBounds(640, 440, 103, 110);

        btnfpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Forgot_Password_70px_1.png"))); // NOI18N
        btnfpassword.setName("btnfpassword"); // NOI18N
        btnfpassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login/icons8_Forgot_Password_100px.png"))); // NOI18N
        btnfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfpasswordActionPerformed(evt);
            }
        });
        login.add(btnfpassword);
        btnfpassword.setBounds(1130, 530, 120, 110);

        rSPanelsSlider1.add(login, "card3");

        interfaz.add(rSPanelsSlider1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        /**
         *Una primera condicion que se llama al metodo de la clase usuario y contar los 
         * usuarios en la BD esto se hace siempre para verificar si es la primera vez que
         * se inicia el programa y así poder saber si se abré el login o el registro.
         */
        if (us.ContarUsuarios() == 0) {
            Registrarjf registrar = new Registrarjf();
            registrar.setVisible(true);
            this.dispose();
        } else {
            rSPanelsSlider1.setPanelSlider(login, RSPanelsSlider.DIRECT.LEFT);
        }
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        /**
         * Obtengo el usuario que se selecciono en el combo box
         * se hace una condicion para verificar sesion enviandole como parametrso
         * el usuario y la contraseña, si regresa true se abré el splah  y posterior el menu
         * de lo contrario se notificara que revise el usuario o ingrese la contraseña correcta.
         */
        String usuario = (String) CMBUsuarios.getSelectedItem();
        if (us.verificarSesion(DigestUtils.md5Hex(PSTcontrasenia.getText()), usuario)) {
            this.dispose();
            splashjf s = new splashjf();
            menujf m = new menujf();
            this.dispose();
            s.setVisible(true);
            s.setLocationRelativeTo(null);
            try {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(10);
                    s.porcentajec.setText(Integer.toString(i) + "%");
                    s.barracargando.setValue(i);
                    if (i == 100) {
                        s.dispose();
                        m.setVisible(true);
                    }
                }

            } catch (InterruptedException e) {

            }
            
        } else {
            JOptionPane.showMessageDialog(null,"Error al ingresar la contraseña","Error",WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btningresarActionPerformed

    private void CMBUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBUsuariosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CMBUsuariosActionPerformed

    private void btnfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfpasswordActionPerformed
        /* Necesario poner un proceso por si olvidó la contraseña
        Sugerencia: reenviar contraseña: usuario123
         */
    }//GEN-LAST:event_btnfpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new inicio_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CMBUsuarios;
    private javax.swing.JPasswordField PSTcontrasenia;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btncomite;
    private javax.swing.JButton btnfpassword;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnsiguiente;
    private jcMousePanel.jcMousePanel inicio;
    private jcMousePanel.jcMousePanel interfaz;
    private jcMousePanel.jcMousePanel login;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
