/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author alexd
 */
public class menuagregarjf extends javax.swing.JFrame {
    ImageIcon menuagregar2 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/menuagregar2.jpg")).getImage());
    /**
     * Creates new form menuagregarjf
     */
    public menuagregarjf() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        if((tamanio.width == 1920) && (tamanio.height == 1080))
        {
            
        }
        else if((tamanio.width == 1366) && (tamanio.height == 768)) //1366.768, alex: 1708.960
        {
            this.setSize(1250, 707);
            jpagregar.setIcon(menuagregar2);
            btnagregarvoluntario.setLocation(275, 330);
            btnagregarproyecto.setLocation(560, 330);
            btnagregarvoluntariado.setLocation(840, 330);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpagregar = new jcMousePanel.jcMousePanel();
        btnagregarvoluntario = new javax.swing.JButton();
        btnagregarproyecto = new javax.swing.JButton();
        btnagregarvoluntariado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jpagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/menuagregar2.jpg"))); // NOI18N
        jpagregar.setVisibleLogo(false);
        jpagregar.setLayout(null);

        btnagregarvoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/Add_User_Male_black_70px.png"))); // NOI18N
        btnagregarvoluntario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/Add_User_Male_black_100px.png"))); // NOI18N
        btnagregarvoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarvoluntarioActionPerformed(evt);
            }
        });
        jpagregar.add(btnagregarvoluntario);
        btnagregarvoluntario.setBounds(230, 280, 110, 100);

        btnagregarproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/project_70px.png"))); // NOI18N
        btnagregarproyecto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/project_100px.png"))); // NOI18N
        btnagregarproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarproyectoActionPerformed(evt);
            }
        });
        jpagregar.add(btnagregarproyecto);
        btnagregarproyecto.setBounds(480, 280, 110, 100);

        btnagregarvoluntariado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/Hand_70px.png"))); // NOI18N
        btnagregarvoluntariado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/Hand_100px.png"))); // NOI18N
        btnagregarvoluntariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarvoluntariadoActionPerformed(evt);
            }
        });
        jpagregar.add(btnagregarvoluntariado);
        btnagregarvoluntariado.setBounds(720, 280, 110, 100);

        getContentPane().add(jpagregar, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarvoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarvoluntarioActionPerformed
        this.dispose();
        agregarjf menu = new agregarjf();
        menu.setVisible(true);
    }//GEN-LAST:event_btnagregarvoluntarioActionPerformed

    private void btnagregarproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarproyectoActionPerformed
        this.dispose();
        agregarpjf proyecto = new agregarpjf();
        proyecto.setVisible(true);
    }//GEN-LAST:event_btnagregarproyectoActionPerformed

    private void btnagregarvoluntariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarvoluntariadoActionPerformed
        this.dispose();
        agregarvjf voluntariado = new agregarvjf();
        voluntariado.setVisible(true);
    }//GEN-LAST:event_btnagregarvoluntariadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuagregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuagregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuagregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuagregarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuagregarjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarproyecto;
    private javax.swing.JButton btnagregarvoluntariado;
    private javax.swing.JButton btnagregarvoluntario;
    private jcMousePanel.jcMousePanel jpagregar;
    // End of variables declaration//GEN-END:variables
}
