/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Nahomi
 */
public class menujf extends javax.swing.JFrame {
    
    //ImageIcon menutam2 = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/opcionestam2.jpg")).getImage());
   ImageIcon menu = new ImageIcon(new ImageIcon(getClass().getResource("/fondos/menuprincipal.jpg")).getImage());
    /**
     * Creates new form menujf
     */
    public menujf() {
        initComponents();
        this.setLocationRelativeTo(null);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        transparencia();
        if ((tamanio.width ==1920)&&(tamanio.height == 1080))
        {
            this.setSize(1565, 880);
            jPanel1.setSize(1565,880);
            rSPanelsSlider1.setSize(1565,880);
            menuprincipal.setSize(1565,880);
            lbmenuprincipal.setSize(1565,880);
            lbmenuprincipal.setIcon(menu);
            this.setLocationRelativeTo(null);
            btnagregar.setLocation(198, 445);
            btneditar.setLocation(515, 430);
            btneliminar.setLocation(838, 415);
            btnbuscar.setLocation(1165, 425);
            btnminimizarmenu.setLocation(1410, 5);
            btnsalirdmenu.setLocation(1480, 5);
        }
        else if((tamanio.width == 1366) && (tamanio.height == 768)) //1366.768, alex: 1708.960
        {
            this.setSize(1256, 706);
            //jpmenu.setIcon(menutam2);
            this.setLocationRelativeTo(null);
            btnagregar.setLocation(133, 345);
            btneditar.setLocation(390, 330);
            btneliminar.setLocation(645, 320);
            btnbuscar.setLocation(917, 330);
            btnminimizarmenu.setLocation(1090, 5);
            btnsalirdmenu.setLocation(1175, 5);
        }
    }
    public void transparencia()
    {
        btnagregar.setOpaque(false);
        btnagregar.setContentAreaFilled(false);
        btnagregar.setBorderPainted(false);
        btneliminar.setOpaque(false);
        btneliminar.setContentAreaFilled(false);
        btneliminar.setBorderPainted(false);
        btneditar.setOpaque(false);
        btneditar.setContentAreaFilled(false);
        btneditar.setBorderPainted(false);
        btnbuscar.setOpaque(false);
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.setBorderPainted(false);
        btnsalirdmenu.setOpaque(false);
        btnsalirdmenu.setContentAreaFilled(false);
        btnsalirdmenu.setBorderPainted(false);
        btnminimizarmenu.setOpaque(false);
        btnminimizarmenu.setContentAreaFilled(false);
        btnminimizarmenu.setBorderPainted(false);
        btnagregarvoluntario.setOpaque(false);
        btnagregarvoluntario.setContentAreaFilled(false);
        btnagregarvoluntario.setBorderPainted(false);
        btnagregarproyecto.setOpaque(false);
        btnagregarproyecto.setContentAreaFilled(false);
        btnagregarproyecto.setBorderPainted(false);
        btnagregarvoluntariado.setOpaque(false);
        btnagregarvoluntariado.setContentAreaFilled(false);
        btnagregarvoluntariado.setBorderPainted(false);
        txtnombreproyecto.setBackground(new Color(0,0,0,0));
        txtdescripcionp.setBackground(new Color (0,0,0,0));
        btnaddproyecto.setOpaque(false);
        btnaddproyecto.setContentAreaFilled(false);
        btnaddproyecto.setBorderPainted(false);
        btnguardarproyecto.setOpaque(false);
        btnguardarproyecto.setContentAreaFilled(false);
        btnguardarproyecto.setBorderPainted(false);
        btnmenu.setOpaque(false);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setBorderPainted(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnminimizarmenu = new javax.swing.JButton();
        btnsalirdmenu = new javax.swing.JButton();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        menuprincipal = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lbmenuprincipal = new javax.swing.JLabel();
        menuagregar = new javax.swing.JPanel();
        btnagregarvoluntario = new javax.swing.JButton();
        btnagregarproyecto = new javax.swing.JButton();
        btnagregarvoluntariado = new javax.swing.JButton();
        lbmenuagregar = new javax.swing.JLabel();
        jpagregarproyecto = new javax.swing.JPanel();
        txtnombreproyecto = new javax.swing.JTextField();
        txtdescripcionp = new javax.swing.JTextField();
        btnaddproyecto = new javax.swing.JButton();
        btnguardarproyecto = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        lbproyectos = new javax.swing.JLabel();
        jpvoluntariadom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproyecto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepuestos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablevoluntarios = new javax.swing.JTable();
        btnguardarvoluntarioado = new javax.swing.JButton();
        btnmenuv = new javax.swing.JButton();
        txtproyecto = new javax.swing.JTextField();
        txtvoluntarios = new javax.swing.JTextField();
        txtmiembros = new javax.swing.JTextField();
        lbvoluntariadom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1565, 880));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1250, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1565, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(1250, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 700));
        jPanel1.setLayout(null);

        btnminimizarmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_30px_1.png"))); // NOI18N
        btnminimizarmenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Chevron_Down_70px.png"))); // NOI18N
        btnminimizarmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizarmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnminimizarmenu);
        btnminimizarmenu.setBounds(1069, 10, 90, 70);

        btnsalirdmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_30px.png"))); // NOI18N
        btnsalirdmenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Close_Window_70px.png"))); // NOI18N
        btnsalirdmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalirdmenuMouseClicked(evt);
            }
        });
        jPanel1.add(btnsalirdmenu);
        btnsalirdmenu.setBounds(1160, 10, 80, 70);

        rSPanelsSlider1.setMaximumSize(new java.awt.Dimension(1565, 880));
        rSPanelsSlider1.setMinimumSize(new java.awt.Dimension(1250, 700));
        rSPanelsSlider1.setPreferredSize(new java.awt.Dimension(1250, 700));

        menuprincipal.setName("menuprincipal"); // NOI18N
        menuprincipal.setLayout(null);

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Add_File_70px.png"))); // NOI18N
        btnagregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnagregar.setName("btnagregar"); // NOI18N
        btnagregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Add_File_100px.png"))); // NOI18N
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        menuprincipal.add(btnagregar);
        btnagregar.setBounds(130, 310, 210, 190);

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Edit_Property_70px.png"))); // NOI18N
        btneditar.setName("btneditar"); // NOI18N
        btneditar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Edit_Property_100px.png"))); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        menuprincipal.add(btneditar);
        btneditar.setBounds(400, 320, 210, 170);

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Search_70px.png"))); // NOI18N
        btnbuscar.setName("btnbuscar"); // NOI18N
        btnbuscar.setPreferredSize(new java.awt.Dimension(150, 25));
        btnbuscar.setRequestFocusEnabled(false);
        btnbuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Search_100px.png"))); // NOI18N
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        menuprincipal.add(btnbuscar);
        btnbuscar.setBounds(910, 310, 230, 170);

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Delete_User_Male_70px.png"))); // NOI18N
        btneliminar.setName("btneliminar"); // NOI18N
        btneliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Delete_User_Male_100px.png"))); // NOI18N
        menuprincipal.add(btneliminar);
        btneliminar.setBounds(640, 300, 230, 180);

        lbmenuprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/opcionestam2.jpg"))); // NOI18N
        lbmenuprincipal.setMaximumSize(new java.awt.Dimension(1250, 700));
        lbmenuprincipal.setMinimumSize(new java.awt.Dimension(1250, 700));
        lbmenuprincipal.setPreferredSize(new java.awt.Dimension(1250, 700));
        lbmenuprincipal.setRequestFocusEnabled(false);
        menuprincipal.add(lbmenuprincipal);
        lbmenuprincipal.setBounds(0, 0, 1250, 700);

        rSPanelsSlider1.add(menuprincipal, "card2");

        menuagregar.setMaximumSize(new java.awt.Dimension(1565, 880));
        menuagregar.setMinimumSize(new java.awt.Dimension(1250, 700));
        menuagregar.setName("menuagregar"); // NOI18N
        menuagregar.setPreferredSize(new java.awt.Dimension(1250, 700));
        menuagregar.setLayout(null);

        btnagregarvoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Add_User_Male_70px_1.png"))); // NOI18N
        btnagregarvoluntario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Add_User_Male_100px.png"))); // NOI18N
        btnagregarvoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarvoluntarioActionPerformed(evt);
            }
        });
        menuagregar.add(btnagregarvoluntario);
        btnagregarvoluntario.setBounds(270, 330, 150, 140);

        btnagregarproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Construction_70px_1.png"))); // NOI18N
        btnagregarproyecto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Construction_100px_1.png"))); // NOI18N
        btnagregarproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarproyectoActionPerformed(evt);
            }
        });
        menuagregar.add(btnagregarproyecto);
        btnagregarproyecto.setBounds(540, 320, 190, 140);

        btnagregarvoluntariado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Hand_70px.png"))); // NOI18N
        btnagregarvoluntariado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Hand_100px.png"))); // NOI18N
        btnagregarvoluntariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarvoluntariadoActionPerformed(evt);
            }
        });
        menuagregar.add(btnagregarvoluntariado);
        btnagregarvoluntariado.setBounds(830, 320, 160, 150);

        lbmenuagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/menu2tam2.jpg"))); // NOI18N
        menuagregar.add(lbmenuagregar);
        lbmenuagregar.setBounds(0, 0, 1250, 700);

        rSPanelsSlider1.add(menuagregar, "card3");

        jpagregarproyecto.setName("jpagregarproyecto"); // NOI18N
        jpagregarproyecto.setLayout(null);

        txtnombreproyecto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtnombreproyecto.setText("Ejemplo");
        jpagregarproyecto.add(txtnombreproyecto);
        txtnombreproyecto.setBounds(80, 245, 710, 40);

        txtdescripcionp.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtdescripcionp.setText("El objetivo del proyecto es.....");
        jpagregarproyecto.add(txtdescripcionp);
        txtdescripcionp.setBounds(80, 380, 710, 260);

        btnaddproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Plus_50px.png"))); // NOI18N
        btnaddproyecto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Plus_75px.png"))); // NOI18N
        jpagregarproyecto.add(btnaddproyecto);
        btnaddproyecto.setBounds(940, 320, 150, 80);

        btnguardarproyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Save_Close_70px.png"))); // NOI18N
        btnguardarproyecto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Save_Close_100px.png"))); // NOI18N
        jpagregarproyecto.add(btnguardarproyecto);
        btnguardarproyecto.setBounds(860, 510, 140, 100);

        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_70px.png"))); // NOI18N
        btnmenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_100px.png"))); // NOI18N
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuMouseClicked(evt);
            }
        });
        jpagregarproyecto.add(btnmenu);
        btnmenu.setBounds(1050, 510, 130, 100);

        lbproyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/proyectos2.jpg"))); // NOI18N
        jpagregarproyecto.add(lbproyectos);
        lbproyectos.setBounds(0, 0, 1250, 700);

        rSPanelsSlider1.add(jpagregarproyecto, "card4");

        jpvoluntariadom.setName("jpvoluntariadom"); // NOI18N
        jpvoluntariadom.setLayout(null);

        tableproyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableproyecto);

        jpvoluntariadom.add(jScrollPane1);
        jScrollPane1.setBounds(50, 170, 550, 210);

        tablepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablepuestos);

        jpvoluntariadom.add(jScrollPane2);
        jScrollPane2.setBounds(50, 460, 550, 210);

        tablevoluntarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablevoluntarios);

        jpvoluntariadom.add(jScrollPane3);
        jScrollPane3.setBounds(640, 170, 570, 210);

        btnguardarvoluntarioado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Save_Close_70px.png"))); // NOI18N
        btnguardarvoluntarioado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu/icons8_Save_Close_100px.png"))); // NOI18N
        jpvoluntariadom.add(btnguardarvoluntarioado);
        btnguardarvoluntarioado.setBounds(740, 490, 180, 100);

        btnmenuv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_70px.png"))); // NOI18N
        btnmenuv.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/generales/icons8_Person_at_Home_100px.png"))); // NOI18N
        btnmenuv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuvMouseClicked(evt);
            }
        });
        jpvoluntariadom.add(btnmenuv);
        btnmenuv.setBounds(970, 490, 160, 120);

        txtproyecto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtproyecto.setText("ejemplo proyecto 1");
        jpvoluntariadom.add(txtproyecto);
        txtproyecto.setBounds(200, 110, 400, 40);

        txtvoluntarios.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtvoluntarios.setText("ejemplo abril torres");
        jpvoluntariadom.add(txtvoluntarios);
        txtvoluntarios.setBounds(830, 110, 370, 40);

        txtmiembros.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtmiembros.setText("ejemplo heidy torres");
        jpvoluntariadom.add(txtmiembros);
        txtmiembros.setBounds(230, 405, 370, 40);

        lbvoluntariadom.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbvoluntariadom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/voluntariadom2.jpg"))); // NOI18N
        lbvoluntariadom.setText("ejemplo heidy torres");
        jpvoluntariadom.add(lbvoluntariadom);
        lbvoluntariadom.setBounds(0, 0, 1250, 700);
        lbvoluntariadom.getAccessibleContext().setAccessibleName("");

        rSPanelsSlider1.add(jpvoluntariadom, "card5");

        jPanel1.add(rSPanelsSlider1);
        rSPanelsSlider1.setBounds(0, 0, 1250, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1250, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarvoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarvoluntarioActionPerformed
        this.dispose();
        agregarjf menu = new agregarjf();
        menu.setVisible(true);
    }//GEN-LAST:event_btnagregarvoluntarioActionPerformed

    private void btnagregarproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarproyectoActionPerformed
    rSPanelsSlider1.setPanelSlider(jpagregarproyecto, RSPanelsSlider.DIRECT.DOWN);
    }//GEN-LAST:event_btnagregarproyectoActionPerformed

    private void btnagregarvoluntariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarvoluntariadoActionPerformed
    rSPanelsSlider1.setPanelSlider(jpvoluntariadom, RSPanelsSlider.DIRECT.DOWN);
    }//GEN-LAST:event_btnagregarvoluntariadoActionPerformed

    private void btnminimizarmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizarmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnminimizarmenuActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        rSPanelsSlider1.setPanelSlider(menuagregar, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnsalirdmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirdmenuMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnsalirdmenuMouseClicked

    private void btnmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseClicked
        rSPanelsSlider1.setPanelSlider(menuprincipal, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnmenuMouseClicked

    private void btnmenuvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuvMouseClicked
        rSPanelsSlider1.setPanelSlider(menuprincipal, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnmenuvMouseClicked

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        this.dispose();
        busquedasjf buscar = new busquedasjf();
        buscar.setVisible(true);
    }//GEN-LAST:event_btnbuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menujf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menujf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddproyecto;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnagregarproyecto;
    private javax.swing.JButton btnagregarvoluntariado;
    private javax.swing.JButton btnagregarvoluntario;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardarproyecto;
    private javax.swing.JButton btnguardarvoluntarioado;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnmenuv;
    private javax.swing.JButton btnminimizarmenu;
    private javax.swing.JButton btnsalirdmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpagregarproyecto;
    private javax.swing.JPanel jpvoluntariadom;
    private javax.swing.JLabel lbmenuagregar;
    private javax.swing.JLabel lbmenuprincipal;
    private javax.swing.JLabel lbproyectos;
    private javax.swing.JLabel lbvoluntariadom;
    private javax.swing.JPanel menuagregar;
    private javax.swing.JPanel menuprincipal;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTable tableproyecto;
    private javax.swing.JTable tablepuestos;
    private javax.swing.JTable tablevoluntarios;
    private javax.swing.JTextField txtdescripcionp;
    private javax.swing.JTextField txtmiembros;
    private javax.swing.JTextField txtnombreproyecto;
    private javax.swing.JTextField txtproyecto;
    private javax.swing.JTextField txtvoluntarios;
    // End of variables declaration//GEN-END:variables
}
