/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Usuario;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Nahomi
 */
public class Registrarjf extends javax.swing.JFrame {

    /**
     * Creates new form registrar
     */
    private Usuario us;

    public void setInfo(int id) {
        ArrayList<Object> datos;
        lblInfo.setText("Actualizar");
        
    }
    
    public Registrarjf() {
        us = new Usuario();//instancio la clase usuario
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);//fondo del jframe
        cmbPuesto.setModel(us.puestos()); // le doy todos los puestos que hay en la Base de datos al combo box
        cmbPuesto.setBackground(new Color(0,0,0,0));//transparencia del combox
        this.setLocationRelativeTo(null);//centralizacion del jframe
        transparencia();//funcion para quitar el fondo de los botones
    }

    /**
     * Metodo para encriptar la contraseña.
     *
     * @param password
     * @return
     */
    private String encriptar(String password) {
        return DigestUtils.md5Hex(password);
    }

    private void transparencia() {
        btnregistrar.setOpaque(false);
        btnregistrar.setContentAreaFilled(false);
        btnregistrar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        TPFcontrasenia = new javax.swing.JPasswordField();
        TPFConfcontrasenia = new javax.swing.JPasswordField();
        nrobot = new javax.swing.JCheckBox();
        btnregistrar = new javax.swing.JButton();
        cmbPuesto = new javax.swing.JComboBox<>();
        lblInfo = new javax.swing.JLabel();
        registrarimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Refgstrarjf"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Alex");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 380, 30));

        txtApellido.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("De León");
        txtApellido.setBorder(null);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 276, 380, 30));

        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("ejemplo@gmail.com");
        txtUsuario.setBorder(null);
        txtUsuario.setName("txtUsuario"); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 300, 30));

        TPFcontrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        TPFcontrasenia.setForeground(new java.awt.Color(153, 153, 153));
        TPFcontrasenia.setText("123456789");
        TPFcontrasenia.setBorder(null);
        getContentPane().add(TPFcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 382, 340, 30));

        TPFConfcontrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        TPFConfcontrasenia.setForeground(new java.awt.Color(153, 153, 153));
        TPFConfcontrasenia.setText("123456789");
        TPFConfcontrasenia.setBorder(null);
        TPFConfcontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPFConfcontraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(TPFConfcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 438, 300, 30));

        nrobot.setBackground(new java.awt.Color(255, 255, 255));
        nrobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrobotActionPerformed(evt);
            }
        });
        getContentPane().add(nrobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 545, -1, -1));

        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar/icons8_Add_User_Male_48px.png"))); // NOI18N
        btnregistrar.setName("btnregistrar"); // NOI18N
        btnregistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar/icons8_Add_User_Male_80px.png"))); // NOI18N
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 542, 120, 80));

        cmbPuesto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        cmbPuesto.setForeground(new java.awt.Color(153, 153, 153));
        cmbPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 485, 390, 40));

        lblInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblInfo.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblInfo.setText("Registrar");
        lblInfo.setOpaque(true);
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 130, 30));

        registrarimg.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        registrarimg.setForeground(new java.awt.Color(102, 102, 102));
        registrarimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/To the Brig!.jpg"))); // NOI18N
        getContentPane().add(registrarimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void TPFConfcontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPFConfcontraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPFConfcontraseniaActionPerformed

    private void nrobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrobotActionPerformed
    /**
     * Este metodo lo que hace es verificar si todos los campos se llenaron
     * correctamente y así evitar errores al insertar el usuario
     *
     * @return
     */
    private boolean verificar() {
        if (txtNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo Nombre está vacío");
            txtNombre.requestFocus();
            return false;
        } else if (txtApellido.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo Apellido está vacío");
            txtApellido.requestFocus();
            return false;
        } else if (cmbPuesto.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "El campo Puesto está vacío");
            cmbPuesto.requestFocus();
            return false;
        } else if (txtUsuario.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo Usuario está vacío");
            txtUsuario.requestFocus();
            return false;
        } else if (TPFcontrasenia.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo contraseña está vacío");
            TPFcontrasenia.requestFocus();
            return false;
        } else if (TPFConfcontrasenia.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo Confirmar contraseña está vacío");
            TPFConfcontrasenia.requestFocus();
            return false;
        } else if (!nrobot.isSelected()) {
            JOptionPane.showMessageDialog(null, "Por favor confirme que no es un robot");
            nrobot.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    //Función para verificarSesion si el correo fue ingresado correctamente
    public boolean verificarEmail(String email) {
        int contArroba = 0, letra = 0;
        boolean arroba = false, mayuscula = false;
        //Ciclo for para recorrer letra por letra el correo ingresado
        for (int i = 0; i < email.length(); i++) {
            letra = email.charAt(i);
            //Condición para verificarSesion si se ingresó alguna letra mayúscula
            if (letra > 64 && letra < 91) {
                JOptionPane.showMessageDialog(null, "Debe escribir su correo en minúsculas");
                mayuscula = true;
            }
            //Condición para contar cuántas arrobas ingresó el usuario
            if (email.charAt(i) == '@') {
                contArroba++;
            }
        }

        //Condición para verificarSesion que el correo sólo tenga una arroba
        if (contArroba == 1) {
            arroba = true;
        } else {
            JOptionPane.showMessageDialog(null, "El correo debe contener una y solo una arroba");
        }

        /*
        Si la cantidad de arrobas ingresadas es 1 y no hay letras mayúsculas ingresadas, la función devolverá
        true y el usuario será ingresado correctamente. De lo contrario el usuario no será ingresado.
         */
        return (arroba) && !mayuscula;
    }

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        /**
         * una condicion para verifica los campos, se obtienen todos los campos
         * de texto en cadenas esto para insertarlos
         */
        if (verificar()) {
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String email = txtUsuario.getText();
            String puesto = (String) cmbPuesto.getSelectedItem();
            String contrasenia = TPFcontrasenia.getText();
            String confirmContrasenia = TPFConfcontrasenia.getText();
            //otra condicion para verifica el email(usuario) para ingresar a la BD
            if (verificarEmail(email)) {
                //otra condicion que verifica si la contraseña coincide con la verificacion de la contraseña esto para evitar que el usuario
                //no se confunda en una letra y así estar mas seguro de su contraseña
                if (contrasenia.equals(confirmContrasenia)) {
                    //otra condicion que sirve para verificar si lo inserto correctamente
                    if (us.insertar(nombre, apellido, encriptar(contrasenia), puesto, email)) {
                        JOptionPane.showMessageDialog(null, "INGRESO REALIZADO CORRECTAMENTE", "Informe", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR EL USUARIO", "Error", JOptionPane.WARNING_MESSAGE);
                    }
                    this.dispose();
                    inicio_login log = new inicio_login();
                    log.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "La contraseña no coincide.");
                }
            }
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TPFConfcontrasenia;
    private javax.swing.JPasswordField TPFcontrasenia;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox<String> cmbPuesto;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JCheckBox nrobot;
    private javax.swing.JLabel registrarimg;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
